// SINGLE SOURCE OF TRUTH
// This file is the authoritative registry of all robot event types.
// It is compiled into Robot.Core.dll and should be referenced from that DLL.
// Do not duplicate this file elsewhere - if source is needed, reference Robot.Core.dll instead.
//
// Linked into: Robot.Core.csproj (modules/robot/core/)
// Referenced by: RobotCore_For_NinjaTrader (via Robot.Core.dll)

using System;
using System.Collections.Generic;

namespace QTSW2.Robot.Core;

public static partial class RobotEventTypes
{
    private static readonly HashSet<string> _allEvents = new(StringComparer.OrdinalIgnoreCase)
    {
        // Engine lifecycle
        "ENGINE_START", "STARTUP_DEPENDENCY_CHECK_FAILED", "ROBOT_BUILD_SIGNATURE", "ENGINE_STOP", "STRATEGY_TERMINATED_BY_NINJATRADER", "ENGINE_STAND_DOWN", "ENGINE_TICK_INVALID_STATE",
        "ENGINE_TICK_STALL_DETECTED", "ENGINE_TICK_STALL_STARTUP", "ENGINE_TICK_STALL_RUNTIME", "ENGINE_TICK_STALL_PLAYBACK", "ENGINE_TICK_STALL_RECOVERED", "ENGINE_TICK_CALLSITE", "ENGINE_PLAYBACK_STALL_QUIESCENCE_ARMED", "ENGINE_PLAYBACK_STALL_QUIESCENCE_STOP_REQUESTED", "ENGINE_PLAYBACK_STALL_QUIESCENCE_DEFERRED_LIVE_EXPOSURE", "ENGINE_PLAYBACK_STALL_QUIESCENCE_DEFERRED_IEA_WORK", "ENGINE_PLAYBACK_STALL_QUIESCENCE_STALE_IEA_WORK_RELEASED", "ENGINE_PLAYBACK_STALL_QUIESCENCE_FORCE_FINALIZE", "ENGINE_PLAYBACK_STALL_QUIESCENCE_FORCE_FINALIZE_LIVE_EXPOSURE", "CONNECTIVITY_SHUTDOWN_REQUESTED", "CONNECTIVITY_SHUTDOWN_DEFERRED", "ENGINE_TIMER_HEARTBEAT",
        "ENGINE_CPU_PROFILE", "ENGINE_CPU_PROFILE_LOCK_SLICES", "ENGINE_AUDIT_SUMMARY", "QUANT_TIER1_RECOVERY_REQUIRED",
        "RISK_LATCH_HYDRATED", "RISK_LATCH_SKIPPED_OBSOLETE", "RISK_LATCH_DELETED_OBSOLETE",
        "RUNTIME_FINGERPRINT", "EXECUTOR_REBOUND", "IEA_OWNERSHIP_CHANGED", "DUPLICATE_STRATEGY_INSTANCE_DETECTED",
        "RECONCILIATION_STUCK", "RECONCILIATION_OSCILLATION", "RECONCILIATION_CONVERGED",
        "IEA_QUEUE_PRESSURE", "CALLBACK_DRAIN_EXEC_ERROR", "CALLBACK_DRAIN_ORDER_ERROR", "CALLBACK_EVENTS_COALESCED",
        "HIGH_FREQUENCY_LOOP_DETECTED", "SUPERVISORY_INSTABILITY_DETECTED",
        "TIMER_LIFECYCLE_STATE_TRANSITION", "TIMER_LIFECYCLE_START_ATTEMPT", "TIMER_LIFECYCLE_START_SKIPPED", "TIMER_LIFECYCLE_STARTED", "TIMER_LIFECYCLE_ERROR",
        "TIMER_GATE_EARLY_RETURN", "TIMER_META_HEARTBEAT", "TIMER_CALLBACK_EXCEPTION",

        // Configuration
        "PROJECT_ROOT_RESOLVED", "LOG_DIR_RESOLVED", "RUN_ID_ASSIGNED", "LOG_DIR_INVALID", "LOGGING_CONFIG_LOADED", "LOGGING_CONFIG_LOAD_FAILED", "SPEC_LOADED",
        "SPEC_INVALID", "SPEC_NAME_LOADED", "HEALTH_MONITOR_CONFIG_LOADED",
        "HEALTH_MONITOR_CONFIG_ERROR", "HEALTH_MONITOR_CONFIG_MISSING", "HEALTH_MONITOR_CONFIG_NULL",
        "HEALTH_MONITOR_DISABLED", "HEALTH_MONITOR_STARTED", "HEALTH_MONITOR_EVALUATION_ERROR",
        "PUSHOVER_CONFIG_MISSING",

        // Timetable
        "TIMETABLE_LOADED", "TIMETABLE_UPDATED", "TIMETABLE_VALIDATED", "TIMETABLE_INVALID",
        "TIMETABLE_INVALID_TRADING_DATE", "TIMETABLE_MISSING_TRADING_DATE",
        "TIMETABLE_TRADING_DATE_MISMATCH", "TRADING_DATE_ROLLED_FORWARD", "TRADING_DATE_ROLLED", "TIMETABLE_APPLY_SKIPPED",
        "TIMETABLE_APPLY_SESSION_INVALID_CRIT", "TIMETABLE_APPLY_SESSION_LOCK_MISMATCH_CRIT", "TIMETABLE_APPLY_ELIGIBILITY_MISSING_CRIT", "TIMETABLE_APPLY_ELIGIBILITY_SESSION_MISMATCH_CRIT",
        "TIMETABLE_ENABLED_STREAM_SET", "TIMETABLE_APPLY_ANCHOR_FILTERED", "TIMETABLE_APPLY_PARTIAL_REFUSAL", "TIMETABLE_PARSING_COMPLETE",
        "TIMETABLE_DERIVED",
        "TIMETABLE_POLL_STALL_DETECTED", "TIMETABLE_POLL_STALL_RECOVERED",

        // Trading date
        "TRADING_DATE_LOCKED", "SESSION_START_DATE_TIMETABLE_AHEAD_CLAMPED",

        // Session Eligibility Freeze
        "SESSION_ELIGIBILITY_FROZEN", "SESSION_ELIGIBILITY_GENERATED_AT_STARTUP", "SESSION_ELIGIBILITY_LOADED", "ELIGIBILITY_MISSING",
        "SESSION_ELIGIBILITY_LOAD_FAILED", "SESSION_ELIGIBILITY_MISSING",
        "SESSION_ELIGIBILITY_TRADING_DATE_MISMATCH", "SESSION_ELIGIBILITY_TRADING_DATE_INVALID",
        "DIRECTIVE_UPDATE_APPLIED", "DIRECTIVE_IGNORED_NOT_ELIGIBLE", "DIRECTIVE_IGNORED_STATE_LOCKED",
        "STREAM_ADDITION_BLOCKED",

        // Streams
        "STREAMS_CREATED", "STREAMS_CREATION_FAILED", "STREAMS_CREATION_SKIPPED",
        "DUPLICATE_STREAM_ID", "STREAM_STAND_DOWN", "STREAM_SKIPPED",

        // Bars
        "BAR_ACCEPTED", "BAR_DATE_MISMATCH", "BAR_PARTIAL_REJECTED",
        "BAR_RECEIVED_BEFORE_DATE_LOCKED", "BAR_RECEIVED_NO_STREAMS",
        "BAR_REJECTION_CONTINUOUS_FUTURE", "BAR_REJECTION_CONTINUOUS_NO_DATE_LOCK",
        "BAR_REJECTION_RATE_HIGH", "BAR_REJECTION_SUMMARY", "BAR_DELIVERY_SUMMARY",
        "BAR_DELIVERY_TO_STREAM", "BAR_ROUTING_DIAGNOSTIC", "BAR_TIME_INTERPRETATION_MISMATCH",
        "BAR_TIME_INTERPRETATION_LOCKED", "BAR_TIME_DETECTION_STARTING",
        "BAR_FLOW_STALLED",

        // BarsRequest
        "BARSREQUEST_REQUESTED", "BARSREQUEST_EXECUTED", "BARSREQUEST_FAILED",
        "BARSREQUEST_SKIPPED", "BARSREQUEST_INITIALIZATION", "BARSREQUEST_RANGE_CHECK",
        "BARSREQUEST_RANGE_DETERMINED", "BARSREQUEST_STREAM_STATUS",
        "BARSREQUEST_FILTER_SUMMARY", "BARSREQUEST_UNEXPECTED_COUNT",
        "BARSREQUEST_ZERO_BARS_DIAGNOSTIC",

        // Pre-hydration
        "PRE_HYDRATION_BARS_LOADED", "PRE_HYDRATION_BARS_FILTERED",
        "PRE_HYDRATION_BARS_SKIPPED", "TIMEZONE_EDGE_CASE_DETECTED", "PRE_HYDRATION_DEFERRED_EXECUTION_CONTEXT_NOT_READY", "PRE_HYDRATION_BARS_SKIPPED_STREAM_STATE",
        "PRE_HYDRATION_BARS_SKIPPED_ACTIVE_STREAM", "PRE_HYDRATION_NO_BARS_AFTER_FILTER_PLAYBACK_FUTURE_ONLY", "PRE_HYDRATION_NO_BARS_AFTER_FILTER",
        "PRE_HYDRATION_WAITING_FOR_BARSREQUEST", "PRE_HYDRATION_WATCHDOG_STUCK", "PRE_HYDRATION_FORCED_TRANSITION",
        "PRE_HYDRATION_COMPLETE_SET", "PRE_HYDRATION_COMPLETE_BLOCK_ENTERED",
        "PRE_HYDRATION_AFTER_COMPLETE_BLOCK", "PRE_HYDRATION_AFTER_VARIABLES",
        "PRE_HYDRATION_BEFORE_RANGE_DIAGNOSTIC", "PRE_HYDRATION_RANGE_START_DIAGNOSTIC",
        "PRE_HYDRATION_HANDLER_TRACE", "PRE_HYDRATION_FAILED",

        // Range computation
        "RANGE_LOCKED", "ENTRY_BREAKOUT_TOO_FAR_REJECTED", "NO_TRADE_BREAKOUT_ALREADY_OCCURRED", "RANGE_COMPUTE_FAILED", "RANGE_COMPUTE_START",
        "RANGE_COMPUTE_NO_BARS_DIAGNOSTIC", "RANGE_COMPUTE_BAR_FILTERING",
        "RANGE_FIRST_BAR_ACCEPTED", "RANGE_INTENT_ASSERT", "RANGE_LOCK_ASSERT",
        "RANGE_INVALIDATED",

        // Gap detection
        "BAR_GAP_DETECTED", "GAP_TOLERANCE_VIOLATION", "GAP_TOLERATED",

        // Execution
        "EXECUTION_MODE_SET", "EXECUTION_CONTEXT_NOT_READY", "EXECUTION_BLOCKED", "EXECUTION_ERROR",         "EXECUTION_FILLED",
        "EXECUTION_PARTIAL_FILL", "EXECUTION_SKIPPED_DUPLICATE",         "EXECUTION_UPDATE_UNKNOWN_ORDER",
        "EXECUTION_UPDATE_ORDER_MAP_RETRY",
        "EXECUTION_UPDATE_SKIPPED_WRONG_INSTANCE", "EXECUTION_UPDATE_WRONG_INSTANCE_DIAGNOSTIC",
        "EXECUTION_UPDATE_GRACE_STARTED", "EXECUTION_UPDATE_GRACE_RETRY", "EXECUTION_UPDATE_GRACE_RESOLVED", "EXECUTION_UPDATE_GRACE_EXPIRED",
        "EXECUTION_DEFERRED_FOR_REGISTRY_RESOLUTION", "EXECUTION_DEFERRED_RETRY", "EXECUTION_DEFERRED_RESOLVED",
        "EXECUTION_DUPLICATE_DETECTED", "EXECUTION_DEDUP_SKIPPED", "EXECUTION_DEDUP_SKIPPED_PERMANENT", "ORDER_UPDATE_DEDUP_SKIPPED", "EXECUTION_RESOLUTION_TIMEOUT",
        "EXEC_ROUTER_ENDPOINT_REGISTERED", "EXEC_ROUTER_ENDPOINT_IDEMPOTENT", "EXEC_ROUTER_ENDPOINT_CONFLICT",
        "ENTRY_AGGREGATION_ATTEMPT", "ENTRY_AGGREGATION_SUCCESS", "ENTRY_AGGREGATION_FAILED",
        "AGG_ENTRY_FILL_ALLOCATED",
        "EXECUTION_UPDATE_MOCK", "EXECUTION_SUMMARY_WRITTEN", "EXECUTION_GATE_INVARIANT_VIOLATION",
        "BREAKOUT_DETECTED_ALREADY_ENTERED", "TRADE_COMPLETED", "TRADE_DEFERRED_POSITION_AUTHORITY", "TRADE_EXECUTED_FROM_DEFERRED", "TRADE_CANCELLED_UNKNOWN_STATE", "TRADE_EXPIRED", "TRADE_BLOCKED_UNKNOWN_STATE",
        "TERMINAL_INTENT_PROTECTIVE_CLEANUP_PENDING", "TERMINAL_INTENT_PROTECTIVE_CLEANUP_ENQUEUED",
        "PROTECTIVE_PARTIAL_EXIT_RETAINED",
        "ENTRY_BLOCKED_RISK", "RISK_CHECK_EVALUATED", "POSITION_FLATTEN_FAIL_CLOSED",
        "EXECUTION_FILL_UNMAPPED", "CRITICAL_UNMAPPED_FILL_DETECTED", "RECOVERY_BLOCKED_INSTRUMENT_LOCKED",
        "EXECUTION_BLOCKED_UNSAFE_STATE", "EXECUTION_BLOCKED_POSITION_AUTHORITY", "EXECUTION_BLOCKED_OVERLAY", "FLATTEN_BLOCKED_UNSAFE_STATE", "FLATTEN_SKIPPED_BROKER_FLAT", "FLATTEN_BLOCKED_OVERLAY",
        "CRITICAL_UNSAFE_STATE_DETECTED", "EXECUTION_SAFETY_MANUAL_UNLOCK", "EXECUTION_SAFETY_MANUAL_UNLOCK_DENIED",
        "HARD_FLATTEN_TRIGGERED", "HARD_FLATTEN_BROKER_FAILED", "HARD_FLATTEN_BROKER_CONTEXT_MISSING", "HARD_FLATTEN_DRYRUN",
        "HARD_FLATTEN_INSTRUMENT_ERROR", "EXECUTION_LOCKED_UNSAFE_STATE", "JOURNAL_INTEGRITY_REPAIR_SUPPRESSED_HARD_FAIL_CLOSED",
        "JOURNAL_INTEGRITY_REPAIR_DEFERRED_PENDING_ALIGNMENT",
        "EXECUTION_GHOST_FILL_DETECTED", "PROTECTIVE_DRIFT_DETECTED", "PROTECTIVE_DRIFT_PENDING_RESIZE",
        "ORPHAN_ORDER_DETECTED", "DUPLICATE_ORDER_SUBMISSION_DETECTED",         "POSITION_DRIFT_DETECTED",
        "EXPOSURE_INTEGRITY_VIOLATION",
        "ORDER_STUCK_DETECTED", "EXECUTION_LATENCY_SPIKE_DETECTED", "RECOVERY_LOOP_DETECTED",

        // Orders
        "ORDER_SUBMITTED", "ORDER_SUBMIT_SUCCESS", "ORDER_SUBMIT_FAIL", "ORDER_SUBMIT_ATTEMPT",
        "ORDER_ACKNOWLEDGED", "ORDER_REJECTED", "ORDER_CANCELLED", "ORDER_CREATED_MARKET_OR_LIMIT", "ORDER_CREATED_VERIFICATION", "ROBOT_ORDER_UPDATE_REGISTRY_RACE", "ROBOT_ORDER_UPDATE_REGISTRY_RACE_INITIALIZED", "STOP_MARKET_RELATIONSHIP_VALIDATION_UNAVAILABLE", "OCO_SIBLING_CANCELLED", "ENTRY_SUBMITTED",
        "PROTECTIVES_PLACED", "PROTECTIVE_ORDERS_SUBMITTED", "PROTECTIVE_ORDERS_FAILED_FLATTENED",
        "STOP_BRACKETS_SUBMITTED", "STOP_BRACKETS_SUBMIT_ATTEMPT", "STOP_BRACKETS_SUBMIT_FAILED",
        "STOP_BRACKETS_PARTIAL_CANCELLED", "STOP_BRACKETS_PARTIAL_CANCEL_FAILED",
        "STOP_MODIFY_ATTEMPT", "STOP_MODIFY_SUCCESS", "STOP_MODIFY_REQUESTED", "STOP_MODIFY_CONFIRMED",
        "STOP_MODIFY_TIMEOUT", "STOP_MODIFY_FAILED", "STOP_MODIFY_FAILED_SNAPSHOT", "STOP_MODIFY_REJECTED", "STOP_MODIFY_PENDING_CLEARED_ON_EXIT",
        "ORDER_UPDATED", "BE_PREFLIGHT_STOP_ORDER_UPDATE",
        "STOP_MODIFY_FAIL", "STOP_MODIFY_SKIPPED", "BE_SKIP_STOP_ALREADY_TIGHTER",
        "BE_TRIGGER_REACHED", "BE_TRIGGER_RETRY_NEEDED", "BE_TRIGGER_FAILED", "BE_TRIGGER_TIMEOUT_ERROR",

        // Execution adapters
        "ADAPTER_SELECTED", "SIM_ACCOUNT_VERIFIED", "LIVE_MODE_BLOCKED",

        // Kill switch
        "KILL_SWITCH_INITIALIZED", "KILL_SWITCH_ACTIVE", "KILL_SWITCH_ERROR_FAIL_CLOSED",

        // Flatten
        "FLATTEN_ATTEMPT", "FLATTEN_SUCCESS", "FLATTEN_FAIL", "FLATTEN_FAILED_ALL_RETRIES", "FLATTEN_DRYRUN",
        "FLATTEN_RECOGNITION_ARMED",

        // Recovery
        "DISCONNECT_FAIL_CLOSED_ENTERED", "DISCONNECT_RECOVERY_STARTED",
        "DISCONNECT_RECOVERY_COMPLETE", "DISCONNECT_RECOVERY_ABORTED",
        "DISCONNECT_RECOVERY_SKIPPED", "DISCONNECT_RECOVERY_WAITING_FOR_SYNC",
        "RECOVERY_ACCOUNT_SNAPSHOT", "RECOVERY_ACCOUNT_SNAPSHOT_FAILED",
        "RECOVERY_ACCOUNT_SNAPSHOT_NULL", "RECOVERY_CANCELLED_ROBOT_ORDERS",
        "RECOVERY_CANCELLED_ROBOT_ORDERS_FAILED", "RECOVERY_ORDERS_PRESERVED",
        "ENTRY_ORDERS_VERIFIED_PRESENT", "ENTRY_ORDERS_MISSING_DETECTED", "ENTRY_ORDERS_RESUBMITTED",
        "ENTRY_ORDERS_RESUBMIT_BLOCKED_POSITION_NOT_FLAT", "ENTRY_ORDERS_RESUBMIT_POSITION_CHECK_ERROR",
        "BREAKOUT_INVALIDATED", "ENTRY_RESUBMIT_BLOCKED_BREAKOUT",
        "RECOVERY_POSITION_RECONCILED",
        "RECOVERY_POSITION_UNMATCHED", "RECOVERY_PROTECTIVE_ORDERS_PLACED",
        "UNMATCHED_POSITION_POLICY_EVALUATION_STARTED", "UNMATCHED_POSITION_POLICY_CANDIDATE_FOUND", "UNMATCHED_POSITION_POLICY_NO_CANDIDATE",
        "UNMATCHED_POSITION_POLICY_ADOPT_APPROVED", "UNMATCHED_POSITION_POLICY_ADOPT_REJECTED",
        "UNMATCHED_POSITION_POLICY_FLATTEN_TRIGGERED", "UNMATCHED_POSITION_POLICY_ADOPT_COMPLETED",
        "UNMATCHED_POSITION_FLATTEN_RESULT",
        "RECOVERY_STREAM_ORDERS_RECONCILED",
        "PROTECTIVE_ORDERS_QUEUED_RECOVERY", "PROTECTIVE_ORDERS_SUBMITTED_FROM_RECOVERY_QUEUE",
        "RECOVERY_PROTECTIVE_TIMEOUT_FLATTENED",

        // Health monitoring
        "CONNECTION_LOST", "CONNECTION_LOST_SUSTAINED", "CONNECTION_CONTEXT", "CONNECTION_RECOVERED", "CONNECTION_RECOVERED_NOTIFICATION",
        "CONNECTIVITY_DAILY_SUMMARY", "CONNECTIVITY_INCIDENT", "CONNECTION_CONFIRMED",
        "DATA_LOSS_DETECTED", "DATA_STALL_RECOVERED",

        // Notifications
        "PUSHOVER_NOTIFY_ENQUEUED", "PUSHOVER_ENDPOINT",
        "CRITICAL_EVENT_REPORTED", "CRITICAL_NOTIFICATION_REJECTED", "CRITICAL_NOTIFICATION_SKIPPED", "CRITICAL_DEDUPE_MISSING_RUN_ID",
        "TEST_NOTIFICATION_SENT", "TEST_NOTIFICATION_SKIPPED", "TEST_NOTIFICATION_TRIGGER_ERROR",

        // Journal
        "JOURNAL_WRITTEN", "JOURNAL_IO_SLOW", "JOURNAL_LOCK_SLOW", "JOURNAL_LATE_SUBMISSION_OBSERVATION", "JOURNAL_INSTRUMENT_KEY_MISMATCH", "INTENT_EXECUTION_INSTRUMENT_MISSING", "EXECUTION_JOURNAL_ERROR", "EXECUTION_JOURNAL_READ_ERROR", "EXECUTION_JOURNAL_CORRUPTION", "EXECUTION_JOURNAL_ADOPTION_INDEX_REBUILT", "EXECUTION_JOURNAL_ADOPTION_INDEX_FALLBACK", "EXECUTION_JOURNAL_ADOPTION_INDEX_REBUILD_FAILED", "EXECUTION_JOURNAL_STALE_RELEASE_CLOSED", "EXECUTION_JOURNAL_POSITION_ALIGNMENT", "RELEASE_BLOCKING_CANDIDATE_AUDIT", "RELEASE_BLOCKING_CANDIDATE_EXCLUDED", "RELEASE_READINESS_INPUT_AUDIT", "RELEASE_READINESS_JOURNAL_PRE_SUM_CHAIN", "RELEASE_SUPPRESSION_DECISION", "EXECUTION_SLIPPAGE_DETECTED",         "JOURNAL_COMPLETION_BLOCKED_BROKER_NOT_FLAT", "JOURNAL_COMPLETION_BLOCKED_ALIGNMENT_INVALID", "JOURNAL_COMPLETION_DECISION", "JOURNAL_PARITY_CHECK", "PENDING_ALIGNMENT_STATE", "JOURNAL_RECONSTRUCTION", "JOURNAL_INTEGRITY_RECOVERED", "RECOVERED_INTENT_CREATED", "RECONCILIATION_RECOVERED_INTENT_FAILED", "RECONCILIATION_RECOVERED_ROW_CLOSED_SUPERSEDED", "AUTHORITY_FRAME_EVALUATED", "POSITION_AUTHORITY_EVALUATED", "POSITION_AUTHORITY_SUMMARY", "JOURNAL_INTEGRITY_FAILED", "JOURNAL_INTEGRITY_DEFERRED", "JOURNAL_INTEGRITY_TRANSIENT_ALIGNMENT", "JOURNAL_INTEGRITY_INVARIANT_CYCLE", "RECONCILIATION_JOURNAL_INTEGRITY_FAILED", "JOURNAL_REOPEN_NORMALIZED", "JOURNAL_ROW_NORMALIZED_OPEN_AFTER_UPSERT",

        // Reconciliation
        "TRADE_RECONCILED", "RECONCILIATION_SKIPPED_HAS_WORKING_ORDERS", "RECONCILIATION_SKIPPED_NON_AUTHORITATIVE_SNAPSHOT", "RECONCILIATION_PASS_SUMMARY", "RECONCILIATION_QTY_STATE", "RECONCILIATION_QTY_MISMATCH", "RECONCILIATION_QTY_MISMATCH_STILL_OPEN", "RECONCILIATION_DEFERRED_BROKER_JOURNAL_ALIGNMENT", "RECONCILIATION_SECONDARY_INSTANCE_SKIPPED", "RECONCILIATION_RESOLVED", "RECONCILIATION_CONTEXT", "RECONCILIATION_ASSEMBLE_MISMATCH_DIAG",
        "PENDING_FILL_BRIDGE_ADDED", "PENDING_FILL_BRIDGE_EXPIRED", "PENDING_FILL_BRIDGE_CONSUMED",
        "RECONCILIATION_ORDER_SOURCE_BREAKDOWN",

        // Slot persistence
        "FORCED_FLATTEN_MARKET_CLOSE", "FORCED_FLATTEN_TRIGGERED", "FORCED_FLATTEN_POSITION_CLOSED", "FORCED_FLATTEN_ORDERS_CANCELLED",
        "FORCED_FLATTEN_FAILED", "FORCED_FLATTEN_BROKER_CONFIRM_DEFERRED", "FORCED_FLATTEN_COMPLETED_LATE_REENTRY_ARMED", "SESSION_CLOSE_GLOBAL_SWEEP_REQUESTED", "SESSION_CLOSE_GLOBAL_SWEEP_SKIPPED", "SESSION_CLOSE_GLOBAL_SWEEP_ERROR", "FORCED_FLATTEN_CONFIRM_PENDING", "FORCED_FLATTEN_RETRY", "FORCED_FLATTEN_EXPOSURE_REMAINING", "MANUAL_FLATTEN_REQUIRED", "FORCED_FLATTEN_ORDERS_CANCEL_ERROR", "FORCED_FLATTEN_VERIFY_ERROR",
        "SESSION_CLOSE_RESOLVED", "SESSION_CLOSE_RESOLUTION_SUCCESS", "SESSION_CLOSE_RESOLUTION_FAILURE", "SESSION_CLOSE_HOLIDAY",
        "SESSION_CLOSE_NO_ELIGIBLE_SEGMENTS", "SESSION_CLOSE_ITERATION_ERROR", "SESSION_CLOSE_EXCEPTION",
        "SESSION_CLOSE_RESOLVE_SKIPPED", "SESSION_CLOSE_FALLBACK_USED", "SESSION_CLOSE_CACHE_MISSING", "SESSION_CLOSE_FALLBACK_FAILED", "SESSION_CLOSE_RESOLVER_FAILED",
        "SESSION_CLOSE_SOURCE_SELECTED", "SESSION_RESOLVED", "FLATTEN_TRIGGER_SET", "SESSION_CLOSE_HOLIDAY_CONFLICT", "SESSION_CLOSE_HOLIDAY_OVERRIDDEN", "SESSION_CLOSE_NO_SESSION_OVERRIDDEN", "SESSION_POLICY_MATERIALIZED", "SESSION_CLOSE_FALLBACK_WARNING",
        "FORCED_FLATTEN_REQUEST_SUBMITTED", "FORCED_FLATTEN_BROKER_TIMEOUT",
        "SUBMIT_MARKET_REENTRY_COMPLETED", "REENTRY_SUBMIT_ENQUEUED", "REENTRY_SUBMIT_FAILED",
        "REENTRY_SUBMITTED", "REENTRY_FILLED", "REENTRY_PROTECTION_DEFERRED_PARTIAL_FILL", "REENTRY_PROTECTIVES_SUBMITTED", "REENTRY_PROTECTION_SUBMIT_FAILED",
        "SESSION_REENTRY_ATTEMPT", "SESSION_REENTRY_BLOCK_BYPASS", "SESSION_REENTRY_BLOCKED", "SESSION_REENTRY_EXECUTED",
        "REENTRY_PROTECTION_ACCEPTED", "REENTRY_PROTECTION_ACCEPTED_CALLBACK", "REENTRY_BATCH_LATCH_ACQUIRED", "REENTRY_BATCH_LATCH_RELEASED", "REENTRY_FAILED", "REENTRY_PROTECTION_FAILED",
        "SLOT_EXPIRED", "SLOT_STATUS_CHANGED", "SLOT_FAILED_RUNTIME",
        "ENTRY_INVALIDATED_POST_LOCK_EXCURSION", "INITIAL_SUBMISSION_BLOCKED_POST_LOCK_EXCURSION", "RANGE_LOCK_TRANSITION_FAILED",

        // Intent exposure coordinator
        "INTENT_EXPOSURE_REGISTERED", "INTENT_EXPOSURE_CLOSED", "INTENT_EXIT_FILL", "INTENT_EXIT_FILL_NO_EXPOSURE", "INTENT_EXPOSURE_REHYDRATED",
        "INTENT_EXIT_VALIDATION_FAILED", "INTENT_PROTECTIVE_FAILURE", "INTENT_PROTECTIVE_FAILURE_FALLBACK",
        "BROKER_EXPOSURE_MISMATCH", "BROKER_EXPOSURE_RECALC_ERROR",
        "CANCEL_INTENT_ORDERS_BLOCKED", "CANCEL_INTENT_ORDERS_MOCK", "CANCEL_INTENT_ORDERS_ENQUEUED", "CANCEL_INTENT_ORDERS_SUCCESS", "CANCEL_INTENT_ORDERS_ERROR", "ENTRY_ORDER_SET_CANCEL_ENQUEUED",
        "FLATTEN_INTENT_ATTEMPT", "FLATTEN_INTENT_SUCCESS", "FLATTEN_INTENT_ERROR",
        "FLATTEN_EMERGENCY_ON_BLOCK", "FLATTEN_EMERGENCY_ON_BLOCK_FAILED",
        "DUPLICATE_INSTANCE_DETECTED", "INTENT_POLICY_MISSING_AT_ORDER_CREATE",
        "INTENT_NOT_FOUND_FLATTEN_FAILED", "UNKNOWN_ORDER_FILL_FLATTEN_FAILED",
        "UNTRACKED_FILL_FLATTEN_FAILED",

        // Logging service
        "LOG_BACKPRESSURE_DROP", "LOG_PIPELINE_METRIC", "LOG_WORKER_LOOP_ERROR", "LOG_WRITE_FAILURE",
        "SNAPSHOT_METRICS", "OWNERSHIP_EVENT_JOURNAL_WRITE_SLOW",
        "LOG_HEALTH_ERROR", "LOG_CONVERSION_ERROR", "LOGGER_CONVERSION_ERROR", "LOGGER_CONVERSION_RETURNED_NULL",
        "LOGGING_INVARIANT_VIOLATION", "UNREGISTERED_EVENT_TYPE", "EXECUTION_EVENT_WRITE_FAILED",

        // Notification failures
        "NOTIFICATION_SEND_FAILED",

        // Account snapshots
        "ACCOUNT_SNAPSHOT_DRYRUN", "ACCOUNT_SNAPSHOT_SLOW", "ACCOUNT_SNAPSHOT_ERROR", "ACCOUNT_SNAPSHOT_LIVE_ERROR",
        "ACCOUNT_SNAPSHOT_LIVE_STUB",

        // Order cancellation
        "CANCEL_ROBOT_ORDERS_DRYRUN", "CANCEL_ROBOT_ORDERS_ERROR",
        "CANCEL_ROBOT_ORDERS_LIVE_ERROR", "CANCEL_ROBOT_ORDERS_LIVE_STUB",
        "CANCEL_ROBOT_ORDERS_MOCK", "ROBOT_ORDERS_CANCELLED",

        // DRYRUN events
        "ENTRY_ORDER_DRYRUN", "STOP_ENTRY_ORDER_DRYRUN", "PROTECTIVE_STOP_DRYRUN",
        "TARGET_ORDER_DRYRUN", "BE_MODIFY_DRYRUN", "BE_INTENT_RESOLUTION_INPUT", "BE_PATH_ACTIVE", "BE_FILTER_TRANSIENT_NO_INTENT", "BE_FILTER_EXCLUDED_PROTECTED_EXPOSURE", "BE_FILTER_EXCLUDED_ACTIVE_EXPOSURE", "ONMARKETDATA_LAST_DIAG",
        "BE_GATE_BLOCKED", "BE_ACCOUNT_EXPOSURE_WITHOUT_INTENT", "BE_INACTIVE_WHILE_EXPOSED",
        "BE_MODIFY_MAX_RETRIES_EXCEEDED", "BE_TICK_STALE_WARNING",
        "BE_TRIGGER_NEAR", "BE_MODIFY_FAILED", "BE_PRE_CHANGE_SNAPSHOT",
        "BE_RATE_LIMIT_SKIPPED", "BE_DEDUPE_SKIPPED", "BE_SCAN_THROTTLED",
        "BE_INTENTS_SCANNED", "BE_STRATEGY_THREAD_ENTERED",
        "BE_PROTECTION_STATE_CHANGED", "BE_PROTECTION_STATE_PRUNED", "PROTECTION_ENQUEUED_BACKLOG_WARN", "PROTECTION_ENQUEUED_BACKLOG_TIMEOUT", "BE_STOP_NOT_VISIBLE_PROTECTION_PENDING", "BE_STOP_VISIBILITY_TIMEOUT", "BE_STOP_VISIBILITY_TIMEOUT_SKIP_ACCOUNT_FLAT",
        "BE_TRIGGER_REACHED", "BE_TRIGGER_RETRY_NEEDED", "BE_TRIGGER_FAILED", "BE_TRIGGER_TIMEOUT_ERROR",

        // Tick/stream state
        "UPDATE_APPLIED",

        // Session
        "SESSION_START_TIME_SET",

        // Gaps
        "GAP_VIOLATIONS_SUMMARY",
        "PROTECTIVE_AUDIT_OK", "PROTECTIVE_AUDIT_FAILED", "PROTECTIVE_MISSING_STOP",
        "PROTECTIVE_STOP_QTY_MISMATCH", "PROTECTIVE_STOP_PRICE_INVALID",
        "PROTECTIVE_MISSING_TARGET", "PROTECTIVE_TARGET_QTY_MISMATCH",
        "PROTECTIVE_CONFLICTING_ORDERS", "PROTECTIVE_RECOVERY_STARTED",
        "PROTECTIVE_RECOVERY_SUBMITTED", "PROTECTIVE_RECOVERY_CONFIRMED",
        "PROTECTIVE_RECOVERY_FAILED", "PROTECTIVE_EMERGENCY_FLATTEN_TRIGGERED",
        "PROTECTIVE_INSTRUMENT_BLOCKED", "PROTECTIVE_AUDIT_CONTEXT", "PROTECTIVE_AUDIT_METRICS", "PROTECTIVE_PENDING_CONVERGENCE",
        "PROTECTIVE_DRIFT_DETECTED", "PROTECTIVE_QUANTITY_MISMATCH_FAIL_CLOSE", "PROTECTIVE_QUANTITY_MISMATCH_FLATTENED",
        "PROTECTIVE_RESIZE_PENDING", "PROTECTIVE_RESIZE_ENQUEUE_FAILED", "PROTECTIVE_ORDER_QUANTITY_CHANGE",
        "PROTECTIVE_ORDERS_CANCELLED_FOR_RECREATE",
        "BE_PENDING_CONVERGENCE", "OWNERSHIP_PENDING_CONVERGENCE", "MISMATCH_PENDING_CONVERGENCE", "REGISTRY_PENDING_CONVERGENCE",
        "RECONCILIATION_MISMATCH_DETECTED", "RECONCILIATION_MISMATCH_PERSISTENT",
        "RECONCILIATION_MISMATCH_FAIL_CLOSED", "RECONCILIATION_MISMATCH_CLEARED",
        "RECONCILIATION_MISMATCH_BLOCKED", "RECONCILIATION_MISMATCH_METRICS",
        "RECONCILIATION_PROGRESS_OBSERVED", "RECONCILIATION_NO_PROGRESS_DETECTED",
        "RECONCILIATION_THROTTLED", "RECONCILIATION_THROTTLE_RESET", "RECONCILIATION_THROTTLE_BACKOFF_UPDATED",
        "RECONCILIATION_HARD_STOPPED", "RECONCILIATION_EXECUTION_CAP_REACHED", "RECONCILIATION_REENTRY_BLOCKED",
        "RECONCILIATION_DEFERRED_PENDING_IEA_EXECUTION", "MISMATCH_EVAL_SKIPPED_PENDING_EXECUTION", "GATE_STALL_SUPPRESSED_IDENTICAL_CYCLE", "OWNERSHIP_RECONCILIATION_BROKER_FLAT_CLOSE", "OWNERSHIP_FLATTEN_EXIT_CLOSE_FAILED", "SNAPSHOT_EMITTER_ERROR",
        "UEA_SHADOW_EVALUATED", "UEA_SHADOW_DISAGREEMENT", "RECONCILIATION_CLASSIFIER_SHADOW_VERDICT",
        "RECONCILIATION_CLASSIFIER_PARITY_DEFERRED", "RECONCILIATION_CLASSIFIER_DISAGREEMENT",
        "STARTUP_RECOVERY_ADOPTION_OCCURRED",
        "STATE_CONSISTENCY_GATE_FOUR_STATE_TSV", "RECONCILIATION_PROGRESS_DELTA", "RECONCILIATION_ATTEMPT_AUDIT",
        "STATE_CONSISTENCY_GATE_RELEASE_BLOCKED_AFTER_FLAT",
        "STATE_CONSISTENCY_GATE_ENGAGED", "STATE_CONSISTENCY_GATE_PERSISTENT_MISMATCH", "STATE_CONSISTENCY_GATE_RECOVERY_FAILED",
        "UEA_ACTIVE_DENY",
        "STATE_CONSISTENCY_GATE_RECONCILIATION_STARTED", "STATE_CONSISTENCY_GATE_RECONCILIATION_RESULT",
        "STATE_CONSISTENCY_GATE_RESTABILIZATION_RESET", "STATE_CONSISTENCY_GATE_STABLE_PENDING_RELEASE", "GATE_RELEASED", "STATE_CONSISTENCY_GATE_RELEASED",
        "STATE_CONSISTENCY_GATE_FAIL_CLOSED_POST_RELEASE_RECHECK_FAILED",
        "ADOPTION_RECOVERY_SCHEDULE_PROBE",
        "RECONCILIATION_BLOCKER_SNAPSHOT", "RECONCILIATION_DECISION_SUMMARY", "RECONCILIATION_SCHEDULER_OUTCOME",
        "RECONCILIATION_LEGACY_CLASSIFIER_GAP", "RECONCILIATION_LEGACY_CLASSIFIER_GAP_MODELING_FAILURE",
        "RECONCILIATION_BLOCKER_INVARIANT_FAILED",
        "RECOVERY_ADOPTION_ZERO_DELTA_BLOCKERS",
        "GATE_RECOVERY_BROKER_FLAT_JOURNAL_CLOSURE",
        "RECONCILIATION_FORCED_CONVERGENCE", "RECONCILIATION_FORCED_CONVERGENCE_SOFT_DEFERRED",
        "ADOPTION_TIMING_AUDIT",

        // Slot gate
        "SLOT_GATE_DIAGNOSTIC",

        // Operator
        "OPERATOR_BANNER",

        // Invariants
        "INVARIANT_VIOLATION", "STREAM_INSTRUMENT_INVARIANT_CHECK", "STREAM_INSTRUMENT_INVARIANT_MISMATCH",

        // Incident persistence
        "INCIDENT_PERSIST_ERROR",

        // Critical execution failures
        "FLATTEN_FAILED_ALL_RETRIES", "DUPLICATE_INSTANCE_DETECTED",
        "FLATTEN_REQUEST_RECEIVED", "FLATTEN_SKIPPED_ACCOUNT_FLAT", "FLATTEN_DIRECTION_INVALID",
        "FLATTEN_ABORTED_INVALID_POSITION_STATE", "FLATTEN_ALREADY_IN_PROGRESS", "FLATTEN_REQUEST_REJECTED_DUPLICATE",
        "FLATTEN_SENT", "FLATTEN_FILL_RECEIVED", "FLATTEN_RESOLVED", "FLATTEN_ORDER_REJECTED", "FLATTEN_LATCH_TIMEOUT",
        "ORDER_REGISTRY_REGISTERED", "ORDER_REGISTRY_FLATTEN_REGISTERED", "ORDER_REGISTRY_ADOPTED", "ORDER_REGISTRY_LIFECYCLE", "ORDER_REGISTRY_EXEC_RESOLVED",
        "ORDER_REGISTRY_BROKER_ID_LINKED", "ORDER_REGISTRY_TERMINAL_LIFECYCLE_RESOLVED_BY_ALIAS", "ORDER_REGISTRY_GHOST_ROW_TERMINALIZED", "ORDER_REGISTRY_LIFECYCLE_BROKER_SYNC",
        "ORDER_REGISTRY_RECOVERY_DEFERRED_FAIL_CLOSED", "ORDER_REGISTRY_RECOVERABLE_UNOWNED_DETECTED", "ORDER_REGISTRY_OWNERSHIP_RECLASSIFIED", "ORDER_REGISTRY_LOOKUP_IEA_MISMATCH",
        "UNOWNED_LIVE_ORDER_DETECTED", "ADOPTION_SCAN_START", "ADOPTION_SKIP_REASON", "ADOPTION_SCAN_SUMMARY", "ADOPTION_DEFERRED_CANDIDATES_EMPTY", "ADOPTION_DEFERRAL_HEARTBEAT_RETRY",
        "ADOPTION_GRACE_EXPIRED_UNOWNED", "ADOPTION_CANDIDATES_EMPTY_NO_BROKER_ORDERS", "FOREIGN_INSTRUMENT_QTSW2_ORDER_SKIPPED",
        "ADOPTION_CANDIDATE_FOUND", "ADOPTION_CANDIDATE_NOT_FOUND", "ADOPTION_SUCCESS", "STALE_QTSW2_ORDER_DETECTED", "ADOPTION_NON_CONVERGENCE_ESCALATED",
        "MANUAL_OR_EXTERNAL_ORDER_DETECTED", "ORDER_LIFECYCLE_TRANSITION_INVALID", "ORDER_LIFECYCLE_TERMINAL_REPLAY_IGNORED",
        "INTENT_LIFECYCLE_TRANSITION", "INTENT_LIFECYCLE_TRANSITION_INVALID", "INTENT_LIFECYCLE_RECONSTRUCTED",
        "EXECUTION_UNOWNED", "REGISTRY_BROKER_DIVERGENCE", "REGISTRY_BROKER_DIVERGENCE_ADOPTED", "ORDER_REGISTRY_CLEANUP", "ORDER_REGISTRY_METRICS",
        "EXECUTION_JOURNAL_EXIT_TYPE_CHANGE", "EXECUTION_JOURNAL_OVERFILL", "INTENT_FILL_UPDATE",
        "COMPLETED_INTENT_LATE_TERMINAL_FILL_RECONCILED",
        "ORDER_CREATED_LIMIT", "ORDER_CREATED_STOPMARKET", "OPPOSITE_ENTRY_CANCELLED_DEFENSIVELY",
        "RECOVERY_STATE_TRANSITION_INVALID", "RECOVERY_TRIGGERED", "RECOVERY_REQUEST_RECEIVED", "RECOVERY_ALREADY_ACTIVE",
        "RECOVERY_ESCALATED", "RECOVERY_GUARD_BLOCKED_NORMAL_MANAGEMENT", "RECOVERY_RECONSTRUCTION_RESULT",
        "RECOVERY_RECONSTRUCTION_IGNORED", "RECOVERY_DECISION_RESUME", "RECOVERY_DECISION_ADOPT",
        "RECOVERY_DECISION_FLATTEN", "RECOVERY_DECISION_HALT", "RECOVERY_FLATTEN_REQUESTED", "RECOVERY_FLATTEN_RESOLVED",
        "RECOVERY_RESOLVED", "RECOVERY_HALTED", "RECOVERY_OPERATOR_ACTION_REQUIRED", "RECOVERY_METRICS",
        "RECOVERY_RECONSTRUCTION_ERROR",
        "BOOTSTRAP_STARTED", "BOOTSTRAP_ADOPTION_ATTEMPT", "BOOTSTRAP_ALREADY_ACTIVE", "BOOTSTRAP_SNAPSHOT_CAPTURED", "BOOTSTRAP_CLASSIFIED",
        "BOOTSTRAP_DECISION_RESUME", "BOOTSTRAP_DECISION_ADOPT", "BOOTSTRAP_DECISION_FLATTEN", "BOOTSTRAP_DECISION_HALT",
        "BOOTSTRAP_ADOPTION_COMPLETED", "BOOTSTRAP_READY_TO_RESUME", "BOOTSTRAP_HALTED", "BOOTSTRAP_OPERATOR_ACTION_REQUIRED",
        "BOOTSTRAP_SNAPSHOT_STALE", "BOOTSTRAP_SNAPSHOT_STALE_RERUN", "BOOTSTRAP_RESULT_IGNORED", "BOOTSTRAP_GUARD_BLOCKED_NORMAL_MANAGEMENT",
        "BOOTSTRAP_FORENSIC_CONTEXT_RECORDED", "BOOTSTRAP_METRICS", "CONNECTION_RECOVERY_REQUIRES_BOOTSTRAP", "CONNECTION_RECOVERY_RESOLVED",
        "SUPERVISORY_STATE_TRANSITION_INVALID", "SUPERVISORY_TRIGGERED", "SUPERVISORY_ESCALATED", "SUPERVISORY_ACTION_REQUESTED",
        "SUPERVISORY_ALREADY_ACTIVE", "SUPERVISORY_POLICY_APPLIED", "INSTRUMENT_COOLDOWN_STARTED", "INSTRUMENT_COOLDOWN_EXPIRED",
        "INSTRUMENT_SUSPENDED", "INSTRUMENT_HALTED", "INSTRUMENT_HALT_CLEARED", "OPERATOR_ACK_REQUIRED", "OPERATOR_ACK_RECEIVED", "OPERATOR_ACK_REJECTED",
        "INSTRUMENT_KILL_SWITCH_ACTIVATED", "INSTRUMENT_UNFROZEN_EXPLICIT", "INSTRUMENT_UNFREEZE_DENIED", "GLOBAL_KILL_SWITCH_ACTIVATED", "GLOBAL_KILL_SWITCH_CLEARED",
        "SUPERVISORY_THRESHOLD_EXCEEDED", "SUPERVISORY_COOLDOWN_ESCALATED", "SUPERVISORY_HALT_ESCALATED",
        "SUPERVISORY_RESUME_ALLOWED", "SUPERVISORY_RESUME_BLOCKED", "SUPERVISORY_METRICS",
        "INTENT_POLICY_MISSING_AT_ORDER_CREATE", "INTENT_NOT_FOUND_FLATTEN_FAILED",
        "UNKNOWN_ORDER_FILL_FLATTEN_FAILED", "UNTRACKED_FILL_FLATTEN_FAILED",
        "EXECUTION_COMMAND_RECEIVED", "EXECUTION_COMMAND_DISPATCHED", "EXECUTION_COMMAND_COMPLETED",
        "EXECUTION_COMMAND_REJECTED", "EXECUTION_COMMAND_UNKNOWN", "EXECUTION_COMMAND_ERROR", "EXECUTION_COMMAND_SKIPPED",
        "EXECUTION_COMMAND_STALLED", "EXECUTION_QUEUE_POISON_DETECTED",
        "DESTRUCTIVE_ACTION_REQUESTED", "DESTRUCTIVE_ACTION_DECISION", "DESTRUCTIVE_ACTION_BLOCKED", "DESTRUCTIVE_ACTION_EXECUTED",
        "CANCEL_SCOPE_APPLIED", "CHECK_ALL_INSTRUMENTS_FLAT_ERROR",
        "IEA_QUEUE_PRESSURE_DIAG", "IEA_EXPENSIVE_PATH_THREAD",
        "IEA_ADOPTION_SCAN_REQUEST_ACCEPTED", "IEA_ADOPTION_SCAN_REQUEST_SKIPPED", "IEA_ADOPTION_SCAN_EXECUTION_STARTED", "IEA_ADOPTION_SCAN_EXECUTION_COMPLETED",
        "IEA_ADOPTION_SCAN_GATE_ANOMALY", "IEA_ADOPTION_SCAN_OFF_WORKER_VIOLATION",
        "IEA_ADOPTION_SCAN_SKIPPED_NO_PROGRESS",
        "IEA_ADOPTION_SCAN_NO_PROGRESS_NOT_SKIPPED",
        "IEA_ADOPTION_SCAN_MUTATION_TIME_ALIGNED",
        "IEA_ADOPTION_SCAN_PHASE_TIMING",
        "IEA_VERIFY_REGISTRY_INTEGRITY_DIAG", "ADOPTION_SAME_STATE_RETRY_WINDOW",
    };
}
