// ⚠️ COPY FROM AUTHORITATIVE SOURCE ⚠️
// This file is a COPY of the authoritative implementation.
// 
// AUTHORITATIVE SOURCE: modules/robot/core/RobotLogEvent.cs
// 
// ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
// All edits must be made in: modules/robot/core/RobotLogEvent.cs
// Then copy the changes here (or use a build script to sync).
//
// This copy exists because NinjaTrader compiles source files directly
// (not via DLL reference). To prevent drift, always edit the authoritative
// source and sync changes here.
//
// Last synced: 2026-01-05

using System;
using System.Collections.Generic;

namespace QTSW2.Robot.Core;

/// <summary>
/// Strict, stable schema for robot log events.
/// One JSON object per line - no multi-line formatting.
/// </summary>
public sealed class RobotLogEvent
{
    /// <summary>ISO8601 UTC timestamp string</summary>
    public string ts_utc { get; set; } = "";

    /// <summary>Log level: DEBUG, INFO, WARN, ERROR</summary>
    public string level { get; set; } = "INFO";

    /// <summary>Source component name: RobotEngine, NinjaTraderAdapter, StrategyHost, etc.</summary>
    public string source { get; set; } = "";

    /// <summary>Instrument identifier: ES, NQ, CL, GC, etc.</summary>
    public string instrument { get; set; } = "";

    /// <summary>Account name if available</summary>
    public string? account { get; set; }

    /// <summary>Current run ID if available</summary>
    public string? run_id { get; set; }

    /// <summary>Short event name/type</summary>
    public string @event { get; set; } = "";

    /// <summary>Human-readable message</summary>
    public string message { get; set; } = "";

    /// <summary>Optional structured payload</summary>
    public Dictionary<string, object?>? data { get; set; }

    public RobotLogEvent()
    {
    }

    public RobotLogEvent(
        DateTimeOffset utcNow,
        string level,
        string source,
        string instrument,
        string eventType,
        string message,
        string? account = null,
        string? runId = null,
        Dictionary<string, object?>? data = null)
    {
        ts_utc = utcNow.ToString("o");
        this.level = level;
        this.source = source;
        this.instrument = instrument ?? "";
        this.account = account;
        this.run_id = runId;
        this.@event = eventType;
        this.message = message;
        this.data = data;
    }
}
