// SINGLE SOURCE OF TRUTH
// This file is the authoritative registry of all robot event types.
// It is compiled into Robot.Core.dll and should be referenced from that DLL.
// Do not duplicate this file elsewhere - if source is needed, reference Robot.Core.dll instead.
//
// Linked into: Robot.Core.csproj (modules/robot/core/)
// Referenced by: RobotCore_For_NinjaTrader (via Robot.Core.dll)

using System;
using System.Collections.Generic;

namespace QTSW2.Robot.Core;

/// <summary>
/// Centralized registry of all robot event types with level assignments.
/// This provides compile-time validation and consistent level assignment.
/// </summary>
public static class RobotEventTypes
{
    /// <summary>
    /// Get the log level for an event type.
    /// Returns "INFO" if event type is unknown (fail-safe).
    /// </summary>
    public static string GetLevel(string eventType)
    {
        if (string.IsNullOrWhiteSpace(eventType))
            return "INFO";
        
        if (_levelMap.TryGetValue(eventType, out var level))
            return level;
        
        // Fallback: use heuristics for unknown events
        var upper = eventType.ToUpperInvariant();
        if (upper.Contains("CRITICAL") || upper.Contains("KILL_SWITCH") || upper.Contains("FLATTEN_FAILED_ALL") ||
            upper.Contains("DUPLICATE_INSTANCE") || upper.Contains("FLATTEN_FAILED"))
            return "CRITICAL";
        if (upper.Contains("ERROR") || upper.Contains("FAIL") || upper.Contains("INVALID") || upper.Contains("VIOLATION"))
            return "ERROR";
        if (upper.Contains("WARN") || upper.Contains("BLOCKED"))
            return "WARN";
        if (upper.Contains("DEBUG") || upper.Contains("DIAGNOSTIC") || upper.Contains("TRACE") || upper.Contains("HEARTBEAT"))
            return "DEBUG";
        
        return "INFO";
    }
    
    /// <summary>
    /// Check if an event type is valid (exists in registry).
    /// </summary>
    public static bool IsValid(string eventType)
    {
        if (string.IsNullOrWhiteSpace(eventType))
            return false;
        
        return _levelMap.ContainsKey(eventType) || _allEvents.Contains(eventType);
    }
    
    /// <summary>
    /// Get all registered event types.
    /// </summary>
    public static IEnumerable<string> GetAllEventTypes()
    {
        return _allEvents;
    }
    
    // Level mapping: event type -> log level
    private static readonly Dictionary<string, string> _levelMap = new(StringComparer.OrdinalIgnoreCase)
    {
        // Engine lifecycle
        ["ENGINE_START"] = "INFO",
        ["STARTUP_DEPENDENCY_CHECK_FAILED"] = "ERROR",
        ["ROBOT_BUILD_SIGNATURE"] = "INFO",
        ["ENGINE_STOP"] = "INFO",
        ["ENGINE_STAND_DOWN"] = "WARN",
        ["ENGINE_TICK_INVALID_STATE"] = "ERROR",
        ["ENGINE_TICK_STALL_DETECTED"] = "ERROR",
        ["ENGINE_TICK_STALL_STARTUP"] = "INFO",
        ["ENGINE_TICK_STALL_RUNTIME"] = "ERROR",
        ["ENGINE_TICK_STALL_RECOVERED"] = "INFO",
        ["ENGINE_TICK_CALLSITE"] = "WARN",  // Watchdog liveness - never drop under backpressure
        ["ENGINE_TIMER_HEARTBEAT"] = "INFO",  // Timer-based heartbeat when market closed (no ticks)
        ["ENGINE_CPU_PROFILE"] = "INFO",  // Opt-in tick/OnBar wall-clock attribution (data/engine_cpu_profile.enabled)
        ["ENGINE_CPU_PROFILE_LOCK_SLICES"] = "INFO",
        ["ENGINE_AUDIT_SUMMARY"] = "INFO",
        // Investigation / ownership audit (no trading-behavior change)
        ["RUNTIME_FINGERPRINT"] = "INFO",
        ["EXECUTOR_REBOUND"] = "INFO",
        ["IEA_OWNERSHIP_CHANGED"] = "INFO",
        ["DUPLICATE_STRATEGY_INSTANCE_DETECTED"] = "CRITICAL",
        ["RECONCILIATION_STUCK"] = "INFO",
        ["RECONCILIATION_OSCILLATION"] = "INFO",
        ["RECONCILIATION_CONVERGED"] = "INFO",
        ["IEA_QUEUE_PRESSURE"] = "INFO",
        ["CALLBACK_DRAIN_EXEC_ERROR"] = "ERROR",
        ["CALLBACK_DRAIN_ORDER_ERROR"] = "ERROR",
        ["CALLBACK_EVENTS_COALESCED"] = "INFO",
        ["HIGH_FREQUENCY_LOOP_DETECTED"] = "INFO",
        ["SUPERVISORY_INSTABILITY_DETECTED"] = "INFO",

        // Timer diagnostics
        ["TIMER_LIFECYCLE_STATE_TRANSITION"] = "INFO",
        ["TIMER_LIFECYCLE_START_ATTEMPT"] = "INFO",
        ["TIMER_LIFECYCLE_START_SKIPPED"] = "INFO",
        ["TIMER_LIFECYCLE_STARTED"] = "INFO",
        ["TIMER_LIFECYCLE_ERROR"] = "ERROR",
        ["TIMER_GATE_EARLY_RETURN"] = "WARN",
        ["TIMER_META_HEARTBEAT"] = "INFO",
        ["TIMER_CALLBACK_EXCEPTION"] = "ERROR",
        
        // Configuration
        ["PROJECT_ROOT_RESOLVED"] = "INFO",
        ["LOG_DIR_RESOLVED"] = "INFO",
        ["LOGGING_CONFIG_LOADED"] = "INFO",
        ["LOGGING_CONFIG_LOAD_FAILED"] = "ERROR",
        ["SPEC_LOADED"] = "INFO",
        ["SPEC_INVALID"] = "ERROR",
        ["SPEC_NAME_LOADED"] = "INFO",
        ["HEALTH_MONITOR_CONFIG_LOADED"] = "INFO",
        ["HEALTH_MONITOR_CONFIG_ERROR"] = "ERROR",
        ["HEALTH_MONITOR_CONFIG_MISSING"] = "WARN",
        ["HEALTH_MONITOR_CONFIG_NULL"] = "WARN",
        ["HEALTH_MONITOR_DISABLED"] = "INFO",
        ["HEALTH_MONITOR_STARTED"] = "INFO",
        ["HEALTH_MONITOR_EVALUATION_ERROR"] = "ERROR",
        ["PUSHOVER_CONFIG_MISSING"] = "WARN",
        
        // Timetable
        ["TIMETABLE_LOADED"] = "INFO",
        ["TIMETABLE_UPDATED"] = "INFO",
        ["TIMETABLE_VALIDATED"] = "INFO",
        ["TIMETABLE_INVALID"] = "ERROR",
        ["TIMETABLE_INVALID_TRADING_DATE"] = "ERROR",
        ["TIMETABLE_MISSING_TRADING_DATE"] = "ERROR",
        ["TIMETABLE_TRADING_DATE_MISMATCH"] = "ERROR",
        ["TRADING_DATE_ROLLED_FORWARD"] = "INFO",
        ["TIMETABLE_APPLY_SKIPPED"] = "INFO",
        ["TIMETABLE_PARSING_COMPLETE"] = "INFO",
        ["TIMETABLE_POLL_STALL_DETECTED"] = "ERROR",
        ["TIMETABLE_POLL_STALL_RECOVERED"] = "INFO",
        
        // Trading date
        ["TRADING_DATE_LOCKED"] = "INFO",
        
        // Session Eligibility Freeze (audit-grade)
        ["SESSION_ELIGIBILITY_FROZEN"] = "INFO",
        ["SESSION_ELIGIBILITY_GENERATED_AT_STARTUP"] = "INFO",
        ["SESSION_ELIGIBILITY_LOADED"] = "INFO",
        ["ELIGIBILITY_MISSING"] = "ERROR",
        ["SESSION_ELIGIBILITY_LOAD_FAILED"] = "ERROR",
        ["SESSION_ELIGIBILITY_MISSING"] = "ERROR",
        ["SESSION_ELIGIBILITY_TRADING_DATE_MISMATCH"] = "ERROR",
        ["SESSION_ELIGIBILITY_TRADING_DATE_INVALID"] = "ERROR",
        ["DIRECTIVE_UPDATE_APPLIED"] = "INFO",
        ["DIRECTIVE_IGNORED_NOT_ELIGIBLE"] = "WARN",
        ["DIRECTIVE_IGNORED_STATE_LOCKED"] = "WARN",
        ["STREAM_ADDITION_BLOCKED"] = "WARN",
        
        // Streams
        ["STREAMS_CREATED"] = "INFO",
        ["STREAMS_CREATION_FAILED"] = "ERROR",
        ["STREAMS_CREATION_SKIPPED"] = "WARN",
        ["DUPLICATE_STREAM_ID"] = "ERROR",
        ["STREAM_STAND_DOWN"] = "WARN",
        ["STREAM_SKIPPED"] = "INFO",
        
        // Bars
        ["BAR_ACCEPTED"] = "DEBUG",
        ["BAR_DATE_MISMATCH"] = "WARN",
        ["BAR_PARTIAL_REJECTED"] = "WARN",
        ["BAR_RECEIVED_BEFORE_DATE_LOCKED"] = "WARN",
        ["BAR_RECEIVED_NO_STREAMS"] = "WARN",
        ["BAR_REJECTION_CONTINUOUS_FUTURE"] = "WARN",
        ["BAR_REJECTION_CONTINUOUS_NO_DATE_LOCK"] = "WARN",
        ["BAR_REJECTION_RATE_HIGH"] = "WARN",
        ["BAR_REJECTION_SUMMARY"] = "INFO",
        ["BAR_DELIVERY_SUMMARY"] = "INFO",
        ["BAR_DELIVERY_TO_STREAM"] = "DEBUG",
        ["BAR_ROUTING_DIAGNOSTIC"] = "DEBUG",
        ["BAR_TIME_INTERPRETATION_MISMATCH"] = "WARN",
        ["BAR_TIME_INTERPRETATION_LOCKED"] = "INFO",
        ["BAR_TIME_DETECTION_STARTING"] = "DEBUG",
        ["BAR_FLOW_STALLED"] = "WARN",
        
        // BarsRequest
        ["BARSREQUEST_REQUESTED"] = "INFO",
        ["BARSREQUEST_EXECUTED"] = "INFO",
        ["BARSREQUEST_FAILED"] = "ERROR",
        ["BARSREQUEST_SKIPPED"] = "INFO",
        ["BARSREQUEST_INITIALIZATION"] = "INFO",
        ["BARSREQUEST_RANGE_CHECK"] = "DEBUG",
        ["BARSREQUEST_RANGE_DETERMINED"] = "INFO",
        ["BARSREQUEST_STREAM_STATUS"] = "DEBUG",
        ["BARSREQUEST_FILTER_SUMMARY"] = "DEBUG",
        ["BARSREQUEST_UNEXPECTED_COUNT"] = "WARN",
        ["BARSREQUEST_ZERO_BARS_DIAGNOSTIC"] = "DEBUG",
        
        // Pre-hydration
        ["PRE_HYDRATION_BARS_LOADED"] = "INFO",
        ["PRE_HYDRATION_BARS_FILTERED"] = "DEBUG",
        ["PRE_HYDRATION_BARS_SKIPPED"] = "DEBUG",
        ["PRE_HYDRATION_BARS_SKIPPED_STREAM_STATE"] = "DEBUG",
        ["PRE_HYDRATION_BARS_SKIPPED_ACTIVE_STREAM"] = "DEBUG",
        ["PRE_HYDRATION_NO_BARS_AFTER_FILTER"] = "WARN",
        ["PRE_HYDRATION_WAITING_FOR_BARSREQUEST"] = "DEBUG",
        ["PRE_HYDRATION_COMPLETE_SET"] = "DEBUG",
        ["PRE_HYDRATION_COMPLETE_BLOCK_ENTERED"] = "DEBUG",
        ["PRE_HYDRATION_AFTER_COMPLETE_BLOCK"] = "DEBUG",
        ["PRE_HYDRATION_AFTER_VARIABLES"] = "DEBUG",
        ["PRE_HYDRATION_BEFORE_RANGE_DIAGNOSTIC"] = "DEBUG",
        ["PRE_HYDRATION_RANGE_START_DIAGNOSTIC"] = "DEBUG",
        ["PRE_HYDRATION_HANDLER_TRACE"] = "DEBUG",
        ["PRE_HYDRATION_FAILED"] = "ERROR",
        
        // Range computation
        ["RANGE_LOCKED"] = "INFO",
        ["RANGE_COMPUTE_FAILED"] = "ERROR",
        ["RANGE_COMPUTE_START"] = "DEBUG",
        ["RANGE_COMPUTE_NO_BARS_DIAGNOSTIC"] = "DEBUG",
        ["RANGE_COMPUTE_BAR_FILTERING"] = "DEBUG",
        ["RANGE_FIRST_BAR_ACCEPTED"] = "DEBUG",
        ["RANGE_INTENT_ASSERT"] = "DEBUG",
        ["RANGE_LOCK_ASSERT"] = "DEBUG",
        ["RANGE_INVALIDATED"] = "WARN",
        
        // Gap detection
        ["BAR_GAP_DETECTED"] = "DEBUG",
        ["GAP_TOLERANCE_VIOLATION"] = "ERROR",
        ["GAP_TOLERATED"] = "WARN",
        
        // Execution
        ["EXECUTION_MODE_SET"] = "INFO",
        ["EXECUTION_BLOCKED"] = "WARN",
        ["EXECUTION_ERROR"] = "ERROR",
        ["EXECUTION_FILL_BLOCKED_TRADING_DATE_NULL"] = "ERROR",
        ["EXECUTION_FILL_UNMAPPED"] = "CRITICAL",
        ["EXECUTION_GHOST_FILL_DETECTED"] = "CRITICAL",
        ["PROTECTIVE_DRIFT_DETECTED"] = "CRITICAL",
        ["ORPHAN_ORDER_DETECTED"] = "CRITICAL",
        ["DUPLICATE_ORDER_SUBMISSION_DETECTED"] = "CRITICAL",
        ["POSITION_DRIFT_DETECTED"] = "CRITICAL",
        ["EXPOSURE_INTEGRITY_VIOLATION"] = "CRITICAL",
        ["ORDER_STUCK_DETECTED"] = "WARN",
        ["EXECUTION_LATENCY_SPIKE_DETECTED"] = "INFO",
        ["RECOVERY_LOOP_DETECTED"] = "WARN",
        ["EXECUTION_FILLED"] = "INFO",
        ["EXECUTION_PARTIAL_FILL"] = "INFO",
        ["ENTRY_AGGREGATION_ATTEMPT"] = "INFO",
        ["ENTRY_AGGREGATION_SUCCESS"] = "INFO",
        ["ENTRY_AGGREGATION_FAILED"] = "ERROR",
        ["AGG_ENTRY_FILL_ALLOCATED"] = "INFO",
        ["EXECUTION_SKIPPED_DUPLICATE"] = "WARN",
        ["EXECUTION_UPDATE_UNKNOWN_ORDER"] = "WARN",
        ["EXECUTION_UPDATE_ORDER_MAP_RETRY"] = "DEBUG",
        ["EXECUTION_UPDATE_SKIPPED_WRONG_INSTANCE"] = "DEBUG",
        ["EXECUTION_UPDATE_WRONG_INSTANCE_DIAGNOSTIC"] = "DEBUG",
        ["EXECUTION_UPDATE_MOCK"] = "DEBUG",
        ["EXECUTION_SUMMARY_WRITTEN"] = "INFO",
        ["EXECUTION_GATE_INVARIANT_VIOLATION"] = "ERROR",
        ["BREAKOUT_DETECTED_ALREADY_ENTERED"] = "WARN",
        ["TRADE_COMPLETED"] = "INFO",
        ["COMPLETED_INTENT_RECEIVED_FILL"] = "CRITICAL",
        ["TERMINAL_INTENT_HAS_WORKING_ORDERS"] = "CRITICAL",
        ["TERMINAL_INTENT_VERIFIED"] = "INFO",
        ["COMPLETED_INTENT_ORDER_UPDATE"] = "WARN",
        ["ENTRY_BLOCKED_RISK"] = "WARN",
        ["RISK_CHECK_EVALUATED"] = "DEBUG",
        ["POSITION_FLATTEN_FAIL_CLOSED"] = "CRITICAL",
        
        // Orders
        ["ORDER_SUBMITTED"] = "INFO",
        ["ORDER_SUBMIT_SUCCESS"] = "INFO",
        ["ORDER_SUBMIT_FAIL"] = "ERROR",
        ["ORDER_SUBMIT_ATTEMPT"] = "DEBUG",
        ["ORDER_ACKNOWLEDGED"] = "INFO",
        ["ORDER_REJECTED"] = "ERROR",
        ["ORDER_CANCELLED"] = "INFO",
        ["OCO_SIBLING_CANCELLED"] = "INFO",
        ["ENTRY_SUBMITTED"] = "INFO",
        ["PROTECTIVES_PLACED"] = "INFO",
        ["PROTECTIVE_ORDERS_SUBMITTED"] = "INFO",
        ["PROTECTIVE_ORDERS_FAILED_FLATTENED"] = "WARN",
        ["STOP_BRACKETS_SUBMITTED"] = "INFO",
        ["STOP_BRACKETS_SUBMIT_ATTEMPT"] = "DEBUG",
        ["STOP_BRACKETS_SUBMIT_FAILED"] = "ERROR",
        ["STOP_MODIFY_ATTEMPT"] = "DEBUG",
        ["STOP_MODIFY_SUCCESS"] = "INFO",
        ["STOP_MODIFY_REQUESTED"] = "INFO",
        ["STOP_MODIFY_CONFIRMED"] = "INFO",
        ["STOP_MODIFY_TIMEOUT"] = "WARN",
        ["STOP_MODIFY_FAILED"] = "ERROR",
        ["STOP_MODIFY_FAILED_SNAPSHOT"] = "DEBUG",
        ["STOP_MODIFY_REJECTED"] = "WARN",
        ["STOP_MODIFY_REVERTED"] = "WARN",
        ["BE_REPLACE_START"] = "INFO",
        ["BE_REPLACE_SUCCESS"] = "INFO",
        ["BE_REPLACE_STOP_FAIL"] = "ERROR",
        ["BE_REPLACE_TARGET_FAIL"] = "WARN",
        ["BE_REPLACE_SKIP"] = "WARN",
        ["BE_CANCEL_REPLACE_START"] = "INFO",
        ["BE_CANCEL_REPLACE_STOP_WORKING"] = "INFO",
        ["BE_CANCEL_REPLACE_DONE"] = "INFO",
        ["STOP_MODIFY_PENDING_CLEARED_ON_EXIT"] = "INFO",
        ["ORDER_UPDATED"] = "INFO",
        ["BE_PREFLIGHT_STOP_ORDER_UPDATE"] = "DEBUG",
        ["STOP_MODIFY_FAIL"] = "ERROR",
        ["STOP_MODIFY_SKIPPED"] = "DEBUG",
        ["BE_SKIP_STOP_ALREADY_TIGHTER"] = "DEBUG",
        ["BE_TRIGGERED"] = "INFO",
        ["BE_TRIGGER_REACHED"] = "INFO", // Legacy alias
        ["BE_TRIGGER_RETRY_NEEDED"] = "INFO",
        ["BE_TRIGGER_FAILED"] = "WARN",
        ["BE_TRIGGER_TIMEOUT_ERROR"] = "ERROR",
        
        // Execution adapters
        ["ADAPTER_SELECTED"] = "INFO",
        ["SIM_ACCOUNT_VERIFIED"] = "INFO",
        ["LIVE_MODE_BLOCKED"] = "ERROR",
        ["EXEC_ROUTER_ENDPOINT_REGISTERED"] = "INFO",
        ["EXEC_ROUTER_ENDPOINT_IDEMPOTENT"] = "DEBUG",
        ["EXEC_ROUTER_ENDPOINT_CONFLICT"] = "CRITICAL",
        ["EXECUTION_UPDATE_GRACE_STARTED"] = "DEBUG",
        ["EXECUTION_UPDATE_GRACE_RETRY"] = "DEBUG",
        ["EXECUTION_UPDATE_GRACE_RESOLVED"] = "INFO",
        ["EXECUTION_UPDATE_GRACE_EXPIRED"] = "CRITICAL",
        ["EXECUTION_DEFERRED_FOR_REGISTRY_RESOLUTION"] = "DEBUG",
        ["EXECUTION_DEFERRED_RETRY"] = "DEBUG",
        ["EXECUTION_DEFERRED_RESOLVED"] = "INFO",
        ["EXECUTION_DUPLICATE_DETECTED"] = "DEBUG",
        ["EXECUTION_DEDUP_SKIPPED"] = "DEBUG",
        ["EXECUTION_DEDUP_SKIPPED_PERMANENT"] = "DEBUG",
        ["ORDER_UPDATE_DEDUP_SKIPPED"] = "DEBUG",
        ["EXECUTION_RESOLUTION_TIMEOUT"] = "CRITICAL",
        ["EXECUTION_ORDERING_METRICS"] = "DEBUG",
        ["STARTUP_RECONCILIATION_REPORT"] = "INFO",
        
        // IEA (Instrument Execution Authority)
        ["IEA_BINDING"] = "INFO",
        ["IEA_HEARTBEAT"] = "DEBUG",
        ["IEA_EXEC_UPDATE_ROUTED"] = "INFO",
        ["IEA_ENQUEUE_AND_WAIT_TIMEOUT"] = "CRITICAL",
        ["IEA_ENQUEUE_AND_WAIT_QUEUE_OVERFLOW"] = "CRITICAL",
        ["IEA_ENQUEUE_AND_WAIT_TIMING"] = "INFO",
        ["IEA_ENQUEUE_REJECTED_INSTRUMENT_BLOCKED"] = "WARN",
        ["IEA_QUEUE_WORKER_ERROR"] = "ERROR",
        ["IEA_ENQUEUE_FAILURE_INSTRUMENT_BLOCKED"] = "CRITICAL",
        ["IEA_BYPASS_ATTEMPTED"] = "ERROR",
        ["EXECUTION_COMMAND_STALLED"] = "CRITICAL",
        ["EXECUTION_QUEUE_POISON_DETECTED"] = "CRITICAL",
        ["IEA_QUEUE_PRESSURE_DIAG"] = "INFO",
        ["IEA_EXPENSIVE_PATH_THREAD"] = "INFO",
        ["IEA_ADOPTION_SCAN_REQUEST_ACCEPTED"] = "INFO",
        ["IEA_ADOPTION_SCAN_REQUEST_SKIPPED"] = "INFO",
        ["IEA_ADOPTION_SCAN_EXECUTION_STARTED"] = "INFO",
        ["IEA_ADOPTION_SCAN_EXECUTION_COMPLETED"] = "INFO",
        ["IEA_ADOPTION_SCAN_GATE_ANOMALY"] = "WARN",
        ["IEA_ADOPTION_SCAN_OFF_WORKER_VIOLATION"] = "ERROR",
        ["IEA_ADOPTION_SCAN_SKIPPED_NO_PROGRESS"] = "INFO",
        ["IEA_VERIFY_REGISTRY_INTEGRITY_DIAG"] = "INFO",
        ["ADOPTION_SAME_STATE_RETRY_WINDOW"] = "WARN",
        ["RECONCILIATION_ASSEMBLE_MISMATCH_DIAG"] = "INFO",

        // Strategy-thread NT action queue (IEA worker → strategy thread marshaling)
        ["NT_ACTION_ENQUEUED"] = "INFO",
        ["NT_ACTION_DUPLICATE_DROPPED"] = "DEBUG",
        ["NT_ACTION_START"] = "DEBUG",
        ["NT_ACTION_SUCCESS"] = "INFO",
        ["FLATTEN_COMMAND_COMPLETED"] = "INFO",
        ["FLATTEN_ORDER_SUBMITTED"] = "INFO",
        ["FLATTEN_BROKER_FLAT_CONFIRMED"] = "INFO",
        ["FLATTEN_BROKER_POSITION_REMAINS"] = "ERROR",
        ["FLATTEN_BROKER_EXPOSURE_PRECHECK"] = "INFO",
        ["FLATTEN_CANONICAL_EXPOSURE"] = "INFO",
        ["BROKER_EXPOSURE_NET_ZERO_MULTI_LEG"] = "WARN",
        ["NT_ACTION_FAIL"] = "ERROR",
        ["NT_ACTION_STRATEGY_THREAD_VIOLATION"] = "CRITICAL",
        ["NT_THREAD_VIOLATION"] = "CRITICAL",
        ["FLATTEN_REQUESTED"] = "INFO",
        ["FLATTEN_SUBMITTED"] = "INFO",
        ["FLATTEN_VERIFY_PASS"] = "INFO",
        ["FLATTEN_VERIFY_FAIL"] = "ERROR",
        ["FLATTEN_FAILED_PERSISTENT"] = "CRITICAL",
        ["FLATTEN_FAILED_PERSISTENT_STILL_OPEN"] = "CRITICAL",
        ["FLATTEN_COORDINATION_OWNER_ASSIGNED"] = "INFO",
        ["FLATTEN_SECONDARY_INSTANCE_SKIPPED"] = "WARN",
        ["FLATTEN_OWNER_TAKEOVER"] = "WARN",
        ["FLATTEN_VERIFY_STILL_OPEN_DEBOUNCED"] = "INFO",
        ["FLATTEN_VERIFY_EXPOSURE_WORSENED"] = "WARN",
        ["STOP_SUBMIT_REQUESTED"] = "INFO",
        ["STOP_SUBMIT_CONFIRMED"] = "INFO",
        ["TARGET_SUBMIT_REQUESTED"] = "INFO",
        ["TARGET_SUBMIT_CONFIRMED"] = "INFO",
        
        // Kill switch
        ["KILL_SWITCH_INITIALIZED"] = "INFO",
        ["KILL_SWITCH_ACTIVE"] = "CRITICAL",
        ["KILL_SWITCH_ERROR_FAIL_CLOSED"] = "CRITICAL",
        
        // Flatten
        ["FLATTEN_ATTEMPT"] = "INFO",
        ["FLATTEN_SUCCESS"] = "INFO",
        ["FLATTEN_FAIL"] = "ERROR",
        ["FLATTEN_FAILED_ALL_RETRIES"] = "CRITICAL",
        ["FLATTEN_DRYRUN"] = "DEBUG",
        ["FLATTEN_EXECUTION_RECOVERED"] = "DEBUG",
        
        // Recovery
        ["DISCONNECT_FAIL_CLOSED_ENTERED"] = "ERROR",
        ["DISCONNECT_RECOVERY_STARTED"] = "INFO",
        ["DISCONNECT_RECOVERY_COMPLETE"] = "INFO",
        ["DISCONNECT_RECOVERY_ABORTED"] = "WARN",
        ["DISCONNECT_RECOVERY_SKIPPED"] = "INFO",
        ["DISCONNECT_RECOVERY_WAITING_FOR_SYNC"] = "INFO",
        ["RECOVERY_ACCOUNT_SNAPSHOT"] = "INFO",
        ["RECOVERY_ACCOUNT_SNAPSHOT_FAILED"] = "ERROR",
        ["RECOVERY_ACCOUNT_SNAPSHOT_NULL"] = "WARN",
        ["RECOVERY_CANCELLED_ROBOT_ORDERS"] = "INFO",
        ["RECOVERY_CANCELLED_ROBOT_ORDERS_FAILED"] = "ERROR",
        ["RECOVERY_ORDERS_PRESERVED"] = "INFO",
        ["ENTRY_ORDERS_VERIFIED_PRESENT"] = "INFO",
        ["ENTRY_ORDERS_MISSING_DETECTED"] = "WARN",
        ["ENTRY_ORDERS_RESUBMITTED"] = "INFO",
        ["ENTRY_ORDERS_RESUBMIT_BLOCKED_POSITION_NOT_FLAT"] = "WARN",
        ["ENTRY_ORDERS_RESUBMIT_POSITION_CHECK_ERROR"] = "ERROR",
        ["BREAKOUT_INVALIDATED"] = "WARN",
        ["ENTRY_RESUBMIT_BLOCKED_BREAKOUT"] = "WARN",
        ["RECOVERY_POSITION_RECONCILED"] = "INFO",
        ["RECOVERY_POSITION_UNMATCHED"] = "WARN",
        ["UNMATCHED_POSITION_POLICY_EVALUATION_STARTED"] = "INFO",
        ["UNMATCHED_POSITION_POLICY_CANDIDATE_FOUND"] = "INFO",
        ["UNMATCHED_POSITION_POLICY_NO_CANDIDATE"] = "WARN",
        ["UNMATCHED_POSITION_POLICY_ADOPT_APPROVED"] = "INFO",
        ["UNMATCHED_POSITION_POLICY_ADOPT_REJECTED"] = "WARN",
        ["UNMATCHED_POSITION_POLICY_FLATTEN_TRIGGERED"] = "WARN",
        ["UNMATCHED_POSITION_POLICY_ADOPT_COMPLETED"] = "INFO",
        ["UNMATCHED_POSITION_FLATTEN_RESULT"] = "INFO",
        ["RECOVERY_PROTECTIVE_ORDERS_PLACED"] = "INFO",
        ["RECOVERY_STREAM_ORDERS_RECONCILED"] = "INFO",
        ["PROTECTIVE_ORDERS_QUEUED_RECOVERY"] = "INFO",
        ["PROTECTIVE_ORDERS_SUBMITTED_FROM_RECOVERY_QUEUE"] = "INFO",
        ["RECOVERY_PROTECTIVE_TIMEOUT_FLATTENED"] = "CRITICAL",
        
        // Health monitoring
        ["CONNECTION_LOST"] = "ERROR",
        ["CONNECTION_LOST_SUSTAINED"] = "ERROR",
        ["CONNECTION_CONTEXT"] = "INFO",
        ["CONNECTION_RECOVERED"] = "INFO",
        ["CONNECTION_RECOVERED_NOTIFICATION"] = "INFO",
        ["CONNECTIVITY_DAILY_SUMMARY"] = "INFO",
        ["CONNECTIVITY_INCIDENT"] = "ERROR",
        ["CONNECTION_CONFIRMED"] = "INFO",
        ["DATA_LOSS_DETECTED"] = "ERROR",
        ["DATA_STALL_RECOVERED"] = "INFO",
        
        // Notifications
        ["PUSHOVER_NOTIFY_ENQUEUED"] = "DEBUG",
        ["PUSHOVER_ENDPOINT"] = "DEBUG",
        ["CRITICAL_EVENT_REPORTED"] = "INFO",
        ["CRITICAL_NOTIFICATION_REJECTED"] = "WARN",
        ["CRITICAL_NOTIFICATION_SKIPPED"] = "WARN",
        ["CRITICAL_DEDUPE_MISSING_RUN_ID"] = "WARN",
        ["TEST_NOTIFICATION_SENT"] = "INFO",
        ["TEST_NOTIFICATION_SKIPPED"] = "WARN",
        ["TEST_NOTIFICATION_TRIGGER_ERROR"] = "ERROR",
        
        // Journal
        ["JOURNAL_WRITTEN"] = "DEBUG",
        ["JOURNAL_INSTRUMENT_KEY_MISMATCH"] = "CRITICAL",
        ["INTENT_EXECUTION_INSTRUMENT_MISSING"] = "CRITICAL",
        ["EXECUTION_JOURNAL_ERROR"] = "ERROR",
        ["EXECUTION_JOURNAL_READ_ERROR"] = "ERROR",
        ["EXECUTION_JOURNAL_CORRUPTION"] = "ERROR",
        ["EXECUTION_JOURNAL_ADOPTION_INDEX_REBUILT"] = "INFO",
        ["EXECUTION_JOURNAL_ADOPTION_INDEX_FALLBACK"] = "WARN",
        ["EXECUTION_JOURNAL_ADOPTION_INDEX_REBUILD_FAILED"] = "WARN",
        ["EXECUTION_SLIPPAGE_DETECTED"] = "INFO",
        
        // Reconciliation
        ["TRADE_RECONCILED"] = "INFO",
        ["RECONCILIATION_SKIPPED_HAS_WORKING_ORDERS"] = "INFO",
        ["RECONCILIATION_PASS_SUMMARY"] = "INFO",
        ["RECONCILIATION_QTY_MISMATCH"] = "CRITICAL",
        ["RECONCILIATION_QTY_MISMATCH_STILL_OPEN"] = "INFO",
        ["RECONCILIATION_SECONDARY_INSTANCE_SKIPPED"] = "INFO",
        ["RECONCILIATION_RESOLVED"] = "INFO",
        ["RECONCILIATION_CONTEXT"] = "INFO",
        ["RECONCILIATION_ORDER_SOURCE_BREAKDOWN"] = "INFO",
        
        // Slot persistence
        ["FORCED_FLATTEN_MARKET_CLOSE"] = "WARN",
        ["FORCED_FLATTEN_TRIGGERED"] = "INFO",
        ["FORCED_FLATTEN_POSITION_CLOSED"] = "INFO",
        ["FORCED_FLATTEN_ORDERS_CANCELLED"] = "INFO",
        ["FORCED_FLATTEN_FAILED"] = "CRITICAL",
        ["FORCED_FLATTEN_RETRY"] = "WARN",
        ["FORCED_FLATTEN_EXPOSURE_REMAINING"] = "CRITICAL",
        ["MANUAL_FLATTEN_REQUIRED"] = "CRITICAL",
        ["FORCED_FLATTEN_ORDERS_CANCEL_ERROR"] = "ERROR",
        ["FORCED_FLATTEN_VERIFY_ERROR"] = "WARN",
        ["SESSION_CLOSE_RESOLVED"] = "INFO",
        ["SESSION_CLOSE_RESOLUTION_SUCCESS"] = "INFO",
        ["SESSION_CLOSE_RESOLUTION_FAILURE"] = "WARN",
        ["SESSION_CLOSE_HOLIDAY"] = "INFO",
        ["SESSION_CLOSE_NO_ELIGIBLE_SEGMENTS"] = "WARN",
        ["SESSION_CLOSE_ITERATION_ERROR"] = "WARN",
        ["SESSION_CLOSE_EXCEPTION"] = "ERROR",
        ["SESSION_CLOSE_RESOLVE_SKIPPED"] = "WARN",
        ["SESSION_CLOSE_FALLBACK_USED"] = "WARN",
        ["SESSION_CLOSE_CACHE_MISSING"] = "ERROR",
        ["SESSION_CLOSE_FALLBACK_FAILED"] = "CRITICAL",
        ["SESSION_CLOSE_RESOLVER_FAILED"] = "ERROR",
        ["REENTRY_SUBMITTED"] = "INFO",
        ["REENTRY_FILLED"] = "INFO",
        ["REENTRY_PROTECTION_ACCEPTED"] = "INFO",
        ["REENTRY_FAILED"] = "ERROR",
        ["REENTRY_PROTECTION_FAILED"] = "ERROR",
        ["SLOT_EXPIRED"] = "INFO",
        ["SLOT_STATUS_CHANGED"] = "INFO",
        ["SLOT_FAILED_RUNTIME"] = "ERROR",
        
        // Intent exposure coordinator
        ["INTENT_EXPOSURE_REGISTERED"] = "INFO",
        ["INTENT_EXPOSURE_CLOSED"] = "INFO",
        ["INTENT_EXIT_FILL"] = "INFO",
        ["INTENT_EXIT_FILL_NO_EXPOSURE"] = "WARN",
        ["INTENT_EXIT_VALIDATION_FAILED"] = "WARN",
        ["INTENT_PROTECTIVE_FAILURE"] = "ERROR",
        ["INTENT_PROTECTIVE_FAILURE_FALLBACK"] = "ERROR",
        ["BROKER_EXPOSURE_MISMATCH"] = "WARN",
        ["BROKER_EXPOSURE_RECALC_ERROR"] = "WARN",
        ["CANCEL_INTENT_ORDERS_BLOCKED"] = "WARN",
        ["CANCEL_INTENT_ORDERS_MOCK"] = "INFO",
        ["CANCEL_INTENT_ORDERS_SUCCESS"] = "INFO",
        ["CANCEL_INTENT_ORDERS_ERROR"] = "ERROR",
        ["FLATTEN_INTENT_ATTEMPT"] = "INFO",
        ["FLATTEN_INTENT_SUCCESS"] = "INFO",
        ["FLATTEN_INTENT_ERROR"] = "ERROR",
        ["FLATTEN_EMERGENCY_ON_BLOCK"] = "INFO",
        ["FLATTEN_EMERGENCY_ON_BLOCK_FAILED"] = "ERROR",
        
        // Logging service
        ["LOG_BACKPRESSURE_DROP"] = "ERROR",
        ["LOG_PIPELINE_METRIC"] = "INFO",
        ["SNAPSHOT_METRICS"] = "INFO",
        ["LOG_WORKER_LOOP_ERROR"] = "ERROR",
        ["LOG_WRITE_FAILURE"] = "ERROR",
        ["LOG_HEALTH_ERROR"] = "ERROR",
        ["LOG_CONVERSION_ERROR"] = "ERROR",
        ["LOGGER_CONVERSION_ERROR"] = "ERROR",
        ["LOGGER_CONVERSION_RETURNED_NULL"] = "ERROR",
        ["LOGGING_INVARIANT_VIOLATION"] = "ERROR",
        ["EXECUTION_EVENT_WRITE_FAILED"] = "ERROR",
        ["UNREGISTERED_EVENT_TYPE"] = "WARN",
        
        // Notification failures
        ["NOTIFICATION_SEND_FAILED"] = "ERROR",
        
        // Account snapshots
        ["ACCOUNT_SNAPSHOT_DRYRUN"] = "DEBUG",
        ["ACCOUNT_SNAPSHOT_ERROR"] = "ERROR",
        ["ACCOUNT_SNAPSHOT_LIVE_ERROR"] = "ERROR",
        ["ACCOUNT_SNAPSHOT_LIVE_STUB"] = "DEBUG",
        
        // Order cancellation
        ["CANCEL_ROBOT_ORDERS_DRYRUN"] = "DEBUG",
        ["CANCEL_ROBOT_ORDERS_ERROR"] = "ERROR",
        ["CANCEL_ROBOT_ORDERS_LIVE_ERROR"] = "ERROR",
        ["CANCEL_ROBOT_ORDERS_LIVE_STUB"] = "DEBUG",
        ["CANCEL_ROBOT_ORDERS_MOCK"] = "DEBUG",
        ["ROBOT_ORDERS_CANCELLED"] = "INFO",
        
        // DRYRUN events
        ["ENTRY_ORDER_DRYRUN"] = "DEBUG",
        ["STOP_ENTRY_ORDER_DRYRUN"] = "DEBUG",
        ["PROTECTIVE_STOP_DRYRUN"] = "DEBUG",
        ["TARGET_ORDER_DRYRUN"] = "DEBUG",
        ["BE_MODIFY_DRYRUN"] = "DEBUG",
        ["BE_PATH_ACTIVE"] = "INFO",
        ["BE_FILTER_EXCLUDED_ACTIVE_EXPOSURE"] = "CRITICAL",
        ["ONMARKETDATA_LAST_DIAG"] = "INFO",
        ["BE_GATE_BLOCKED"] = "WARN",
        ["BE_ACCOUNT_EXPOSURE_WITHOUT_INTENT"] = "WARN",
        ["BE_INACTIVE_WHILE_EXPOSED"] = "WARN",
        ["BE_MODIFY_MAX_RETRIES_EXCEEDED"] = "CRITICAL",
        ["BE_TICK_STALE_WARNING"] = "WARN",
        ["BE_TRIGGER_NEAR"] = "INFO",
        ["BE_MODIFY_FAILED"] = "WARN",
        ["BE_MODIFY_RETRY"] = "INFO",
        ["BE_PRE_CHANGE_SNAPSHOT"] = "DEBUG",
        ["BE_RATE_LIMIT_SKIPPED"] = "DEBUG",
        ["BE_DEDUPE_SKIPPED"] = "DEBUG",
        ["BE_SCAN_THROTTLED"] = "DEBUG",
        ["BE_INTENTS_SCANNED"] = "DEBUG",
        ["BE_STRATEGY_THREAD_ENTERED"] = "DEBUG",
        ["BE_PROTECTION_STATE_CHANGED"] = "DEBUG",
        ["BE_PROTECTION_STATE_PRUNED"] = "DEBUG",
        ["PROTECTION_ENQUEUED_BACKLOG_WARN"] = "WARN",
        ["PROTECTION_ENQUEUED_BACKLOG_TIMEOUT"] = "CRITICAL",
        ["BE_STOP_NOT_VISIBLE_PROTECTION_PENDING"] = "DEBUG",
        ["BE_STOP_VISIBILITY_TIMEOUT"] = "CRITICAL",
        ["BE_STOP_VISIBILITY_TIMEOUT_SKIP_ACCOUNT_FLAT"] = "INFO",
        
        // Tick/stream state
        ["UPDATE_APPLIED"] = "DEBUG",
        
        // Session
        ["SESSION_START_TIME_SET"] = "INFO",
        
        // Gaps
        ["GAP_VIOLATIONS_SUMMARY"] = "WARN",

        // Protective coverage audit (Gap 3)
        ["PROTECTIVE_AUDIT_OK"] = "DEBUG",
        ["PROTECTIVE_AUDIT_FAILED"] = "ERROR",
        ["PROTECTIVE_MISSING_STOP"] = "CRITICAL",
        ["PROTECTIVE_STOP_QTY_MISMATCH"] = "CRITICAL",
        ["PROTECTIVE_STOP_PRICE_INVALID"] = "CRITICAL",
        ["PROTECTIVE_MISSING_TARGET"] = "WARN",
        ["PROTECTIVE_TARGET_QTY_MISMATCH"] = "WARN",
        ["PROTECTIVE_CONFLICTING_ORDERS"] = "CRITICAL",
        ["PROTECTIVE_RECOVERY_STARTED"] = "INFO",
        ["PROTECTIVE_RECOVERY_SUBMITTED"] = "INFO",
        ["PROTECTIVE_RECOVERY_CONFIRMED"] = "INFO",
        ["PROTECTIVE_RECOVERY_FAILED"] = "ERROR",
        ["PROTECTIVE_EMERGENCY_FLATTEN_TRIGGERED"] = "CRITICAL",
        ["PROTECTIVE_INSTRUMENT_BLOCKED"] = "WARN",
        ["PROTECTIVE_AUDIT_METRICS"] = "INFO",

        // Mismatch escalation (Gap 4)
        ["RECONCILIATION_MISMATCH_DETECTED"] = "WARN",
        ["RECONCILIATION_MISMATCH_PERSISTENT"] = "CRITICAL",
        ["RECONCILIATION_MISMATCH_FAIL_CLOSED"] = "CRITICAL",
        ["RECONCILIATION_MISMATCH_CLEARED"] = "INFO",
        ["RECONCILIATION_MISMATCH_BLOCKED"] = "WARN",
        ["RECONCILIATION_MISMATCH_METRICS"] = "INFO",
        ["RECONCILIATION_PROGRESS_OBSERVED"] = "INFO",
        ["RECONCILIATION_NO_PROGRESS_DETECTED"] = "INFO",
        ["RECONCILIATION_THROTTLED"] = "INFO",
        ["RECONCILIATION_THROTTLE_RESET"] = "INFO",
        ["RECONCILIATION_THROTTLE_BACKOFF_UPDATED"] = "INFO",
        ["RECONCILIATION_HARD_STOPPED"] = "WARN",
        ["RECONCILIATION_EXECUTION_CAP_REACHED"] = "INFO",
        ["RECONCILIATION_REENTRY_BLOCKED"] = "INFO",
        ["STARTUP_RECOVERY_ADOPTION_OCCURRED"] = "INFO",

        // Slot gate
        ["SLOT_GATE_DIAGNOSTIC"] = "DEBUG",
        
        // Operator
        ["OPERATOR_BANNER"] = "INFO",
        
        // Invariants
        ["INVARIANT_VIOLATION"] = "ERROR",
        ["STREAM_INSTRUMENT_INVARIANT_CHECK"] = "INFO",
        ["STREAM_INSTRUMENT_INVARIANT_MISMATCH"] = "CRITICAL",
        
        // Incident persistence
        ["INCIDENT_PERSIST_ERROR"] = "ERROR",
        
        // Critical execution failures (highest severity)
        ["DUPLICATE_INSTANCE_DETECTED"] = "CRITICAL",
        ["INTENT_POLICY_MISSING_AT_ORDER_CREATE"] = "CRITICAL",
        ["INTENT_NOT_FOUND_FLATTEN_FAILED"] = "CRITICAL",
        ["UNKNOWN_ORDER_FILL_FLATTEN_FAILED"] = "CRITICAL",
        ["UNTRACKED_FILL_FLATTEN_FAILED"] = "CRITICAL",

        // IEA Flatten Authority
        ["FLATTEN_REQUEST_RECEIVED"] = "INFO",
        ["FLATTEN_SKIPPED_ACCOUNT_FLAT"] = "INFO",
        ["FLATTEN_DIRECTION_INVALID"] = "CRITICAL",
        ["FLATTEN_ABORTED_INVALID_POSITION_STATE"] = "CRITICAL",
        ["FLATTEN_ALREADY_IN_PROGRESS"] = "WARN",
        ["FLATTEN_REQUEST_REJECTED_DUPLICATE"] = "WARN",
        ["FLATTEN_SENT"] = "INFO",
        ["FLATTEN_FILL_RECEIVED"] = "INFO",
        ["FLATTEN_RESOLVED"] = "INFO",
        ["FLATTEN_ORDER_REJECTED"] = "WARN",
        ["FLATTEN_LATCH_TIMEOUT"] = "CRITICAL",

        // IEA Order Registry (Execution Ownership Phase 1)
        ["ORDER_REGISTRY_REGISTERED"] = "INFO",
        ["ORDER_REGISTRY_FLATTEN_REGISTERED"] = "INFO",
        ["ORDER_REGISTRY_ADOPTED"] = "INFO",
        ["ORDER_REGISTRY_LIFECYCLE"] = "INFO",
        ["ORDER_REGISTRY_EXEC_RESOLVED"] = "INFO",
        ["ADOPTED_ORDER_FILL_RESOLVED_CROSS_INSTANCE"] = "INFO",
        ["ADOPTED_ORDER_FILL_JOURNALED"] = "INFO",
        ["ADOPTED_ORDER_FILL_UNRESOLVED"] = "WARN",
        // Phase 2: Ownership policy, restart adoption, anomaly classification
        ["UNOWNED_LIVE_ORDER_DETECTED"] = "CRITICAL",
        ["ADOPTION_SCAN_START"] = "INFO",
        ["ADOPTION_SCAN_SUMMARY"] = "INFO",
        ["ADOPTION_DEFERRED_CANDIDATES_EMPTY"] = "INFO",
        ["ADOPTION_GRACE_EXPIRED_UNOWNED"] = "WARN",
        ["ADOPTION_CANDIDATES_EMPTY_NO_BROKER_ORDERS"] = "INFO",
        ["FOREIGN_INSTRUMENT_QTSW2_ORDER_SKIPPED"] = "DEBUG",
        ["ADOPTION_CANDIDATE_FOUND"] = "INFO",
        ["ADOPTION_CANDIDATE_NOT_FOUND"] = "WARN",
        ["STALE_QTSW2_ORDER_DETECTED"] = "CRITICAL",
        ["ADOPTION_NON_CONVERGENCE_ESCALATED"] = "CRITICAL",
        // Explicit level: name contains "HEARTBEAT" — without map entry, GetLevel() heuristic would classify as DEBUG.
        ["ADOPTION_DEFERRAL_HEARTBEAT_RETRY"] = "INFO",
        ["MANUAL_OR_EXTERNAL_ORDER_DETECTED"] = "CRITICAL",
        ["ORDER_LIFECYCLE_TRANSITION_INVALID"] = "ERROR",
        ["EXECUTION_UNOWNED"] = "CRITICAL",
        ["REGISTRY_BROKER_DIVERGENCE"] = "CRITICAL",
        ["REGISTRY_BROKER_DIVERGENCE_ADOPTED"] = "INFO",
        ["ORDER_REGISTRY_CLEANUP"] = "DEBUG",
        ["ORDER_REGISTRY_METRICS"] = "INFO",

        // Phase 3: Deterministic Recovery
        ["RECOVERY_STATE_TRANSITION_INVALID"] = "CRITICAL",
        ["RECOVERY_TRIGGERED"] = "CRITICAL",
        ["RECOVERY_REQUEST_RECEIVED"] = "INFO",
        ["RECOVERY_ALREADY_ACTIVE"] = "WARN",
        ["RECOVERY_ESCALATED"] = "WARN",
        ["RECOVERY_GUARD_BLOCKED_NORMAL_MANAGEMENT"] = "WARN",
        ["RECOVERY_RECONSTRUCTION_RESULT"] = "INFO",
        ["RECOVERY_RECONSTRUCTION_IGNORED"] = "WARN",
        ["RECOVERY_DECISION_RESUME"] = "INFO",
        ["RECOVERY_DECISION_ADOPT"] = "INFO",
        ["RECOVERY_DECISION_FLATTEN"] = "INFO",
        ["RECOVERY_DECISION_HALT"] = "CRITICAL",
        ["RECOVERY_FLATTEN_REQUESTED"] = "INFO",
        ["RECOVERY_FLATTEN_RESOLVED"] = "INFO",
        ["RECOVERY_RESOLVED"] = "INFO",
        ["RECOVERY_HALTED"] = "CRITICAL",
        ["RECOVERY_OPERATOR_ACTION_REQUIRED"] = "CRITICAL",
        ["RECOVERY_METRICS"] = "INFO",
        ["RECOVERY_RECONSTRUCTION_ERROR"] = "ERROR",

        // Phase 4 Bootstrap
        ["BOOTSTRAP_STARTED"] = "INFO",
        ["BOOTSTRAP_ADOPTION_ATTEMPT"] = "INFO",
        ["BOOTSTRAP_ALREADY_ACTIVE"] = "WARN",
        ["BOOTSTRAP_SNAPSHOT_CAPTURED"] = "INFO",
        ["BOOTSTRAP_CLASSIFIED"] = "INFO",
        ["BOOTSTRAP_DECISION_RESUME"] = "INFO",
        ["BOOTSTRAP_DECISION_ADOPT"] = "INFO",
        ["BOOTSTRAP_DECISION_FLATTEN"] = "INFO",
        ["BOOTSTRAP_DECISION_HALT"] = "CRITICAL",
        ["BOOTSTRAP_ADOPTION_COMPLETED"] = "INFO",
        ["BOOTSTRAP_READY_TO_RESUME"] = "INFO",
        ["BOOTSTRAP_HALTED"] = "CRITICAL",
        ["BOOTSTRAP_OPERATOR_ACTION_REQUIRED"] = "CRITICAL",
        ["BOOTSTRAP_SNAPSHOT_STALE"] = "WARN",
        ["BOOTSTRAP_SNAPSHOT_STALE_RERUN"] = "INFO",
        ["BOOTSTRAP_RESULT_IGNORED"] = "WARN",
        ["BOOTSTRAP_GUARD_BLOCKED_NORMAL_MANAGEMENT"] = "WARN",
        ["BOOTSTRAP_FORENSIC_CONTEXT_RECORDED"] = "INFO",
        ["BOOTSTRAP_METRICS"] = "INFO",
        ["CONNECTION_RECOVERY_REQUIRES_BOOTSTRAP"] = "INFO",
        ["CONNECTION_RECOVERY_RESOLVED"] = "INFO",

        // Phase 5 Supervisory
        ["SUPERVISORY_STATE_TRANSITION_INVALID"] = "CRITICAL",
        ["SUPERVISORY_TRIGGERED"] = "WARN",
        ["SUPERVISORY_ESCALATED"] = "WARN",
        ["SUPERVISORY_ACTION_REQUESTED"] = "INFO",
        ["SUPERVISORY_ALREADY_ACTIVE"] = "WARN",
        ["SUPERVISORY_POLICY_APPLIED"] = "INFO",
        ["INSTRUMENT_COOLDOWN_STARTED"] = "INFO",
        ["INSTRUMENT_COOLDOWN_EXPIRED"] = "INFO",
        ["INSTRUMENT_SUSPENDED"] = "WARN",
        ["INSTRUMENT_HALTED"] = "CRITICAL",
        ["INSTRUMENT_HALT_CLEARED"] = "INFO",
        ["OPERATOR_ACK_REQUIRED"] = "CRITICAL",
        ["OPERATOR_ACK_RECEIVED"] = "INFO",
        ["OPERATOR_ACK_REJECTED"] = "WARN",
        ["INSTRUMENT_KILL_SWITCH_ACTIVATED"] = "CRITICAL",
        ["GLOBAL_KILL_SWITCH_ACTIVATED"] = "CRITICAL",
        ["GLOBAL_KILL_SWITCH_CLEARED"] = "INFO",
        ["SUPERVISORY_THRESHOLD_EXCEEDED"] = "WARN",
        ["SUPERVISORY_COOLDOWN_ESCALATED"] = "WARN",
        ["SUPERVISORY_HALT_ESCALATED"] = "CRITICAL",
        ["SUPERVISORY_RESUME_ALLOWED"] = "INFO",
        ["SUPERVISORY_RESUME_BLOCKED"] = "WARN",
        ["SUPERVISORY_METRICS"] = "INFO",
    };
    
    // All registered event types (for validation)
    private static readonly HashSet<string> _allEvents = new(StringComparer.OrdinalIgnoreCase)
    {
        // Engine lifecycle
        "ENGINE_START", "STARTUP_DEPENDENCY_CHECK_FAILED", "ROBOT_BUILD_SIGNATURE", "ENGINE_STOP", "ENGINE_STAND_DOWN", "ENGINE_TICK_INVALID_STATE",
        "ENGINE_TICK_STALL_DETECTED", "ENGINE_TICK_STALL_STARTUP", "ENGINE_TICK_STALL_RUNTIME", "ENGINE_TICK_STALL_RECOVERED", "ENGINE_TICK_CALLSITE", "ENGINE_TIMER_HEARTBEAT",
        "ENGINE_CPU_PROFILE", "ENGINE_CPU_PROFILE_LOCK_SLICES", "ENGINE_AUDIT_SUMMARY",
        "RUNTIME_FINGERPRINT", "EXECUTOR_REBOUND", "IEA_OWNERSHIP_CHANGED", "DUPLICATE_STRATEGY_INSTANCE_DETECTED",
        "RECONCILIATION_STUCK", "RECONCILIATION_OSCILLATION", "RECONCILIATION_CONVERGED",
        "IEA_QUEUE_PRESSURE", "CALLBACK_DRAIN_EXEC_ERROR", "CALLBACK_DRAIN_ORDER_ERROR", "CALLBACK_EVENTS_COALESCED",
        "HIGH_FREQUENCY_LOOP_DETECTED", "SUPERVISORY_INSTABILITY_DETECTED",
        "TIMER_LIFECYCLE_STATE_TRANSITION", "TIMER_LIFECYCLE_START_ATTEMPT", "TIMER_LIFECYCLE_START_SKIPPED", "TIMER_LIFECYCLE_STARTED", "TIMER_LIFECYCLE_ERROR",
        "TIMER_GATE_EARLY_RETURN", "TIMER_META_HEARTBEAT", "TIMER_CALLBACK_EXCEPTION",
        
        // Configuration
        "PROJECT_ROOT_RESOLVED", "LOG_DIR_RESOLVED", "LOGGING_CONFIG_LOADED", "LOGGING_CONFIG_LOAD_FAILED", "SPEC_LOADED",
        "SPEC_INVALID", "SPEC_NAME_LOADED", "HEALTH_MONITOR_CONFIG_LOADED",
        "HEALTH_MONITOR_CONFIG_ERROR", "HEALTH_MONITOR_CONFIG_MISSING", "HEALTH_MONITOR_CONFIG_NULL",
        "HEALTH_MONITOR_DISABLED", "HEALTH_MONITOR_STARTED", "HEALTH_MONITOR_EVALUATION_ERROR",
        "PUSHOVER_CONFIG_MISSING",
        
        // Timetable
        "TIMETABLE_LOADED", "TIMETABLE_UPDATED", "TIMETABLE_VALIDATED", "TIMETABLE_INVALID",
        "TIMETABLE_INVALID_TRADING_DATE", "TIMETABLE_MISSING_TRADING_DATE",
        "TIMETABLE_TRADING_DATE_MISMATCH", "TRADING_DATE_ROLLED_FORWARD", "TIMETABLE_APPLY_SKIPPED", "TIMETABLE_PARSING_COMPLETE",
        "TIMETABLE_POLL_STALL_DETECTED", "TIMETABLE_POLL_STALL_RECOVERED",
        
        // Trading date
        "TRADING_DATE_LOCKED",
        
        // Session Eligibility Freeze
        "SESSION_ELIGIBILITY_FROZEN", "SESSION_ELIGIBILITY_GENERATED_AT_STARTUP", "SESSION_ELIGIBILITY_LOADED", "ELIGIBILITY_MISSING",
        "SESSION_ELIGIBILITY_LOAD_FAILED", "SESSION_ELIGIBILITY_MISSING",
        "SESSION_ELIGIBILITY_TRADING_DATE_MISMATCH", "SESSION_ELIGIBILITY_TRADING_DATE_INVALID",
        "DIRECTIVE_UPDATE_APPLIED", "DIRECTIVE_IGNORED_NOT_ELIGIBLE", "DIRECTIVE_IGNORED_STATE_LOCKED",
        "STREAM_ADDITION_BLOCKED",
        
        // Streams
        "STREAMS_CREATED", "STREAMS_CREATION_FAILED", "STREAMS_CREATION_SKIPPED",
        "DUPLICATE_STREAM_ID", "STREAM_STAND_DOWN", "STREAM_SKIPPED",
        
        // Bars
        "BAR_ACCEPTED", "BAR_DATE_MISMATCH", "BAR_PARTIAL_REJECTED",
        "BAR_RECEIVED_BEFORE_DATE_LOCKED", "BAR_RECEIVED_NO_STREAMS",
        "BAR_REJECTION_CONTINUOUS_FUTURE", "BAR_REJECTION_CONTINUOUS_NO_DATE_LOCK",
        "BAR_REJECTION_RATE_HIGH", "BAR_REJECTION_SUMMARY", "BAR_DELIVERY_SUMMARY",
        "BAR_DELIVERY_TO_STREAM", "BAR_ROUTING_DIAGNOSTIC", "BAR_TIME_INTERPRETATION_MISMATCH",
        "BAR_TIME_INTERPRETATION_LOCKED", "BAR_TIME_DETECTION_STARTING",
        "BAR_FLOW_STALLED",
        
        // BarsRequest
        "BARSREQUEST_REQUESTED", "BARSREQUEST_EXECUTED", "BARSREQUEST_FAILED",
        "BARSREQUEST_SKIPPED", "BARSREQUEST_INITIALIZATION", "BARSREQUEST_RANGE_CHECK",
        "BARSREQUEST_RANGE_DETERMINED", "BARSREQUEST_STREAM_STATUS",
        "BARSREQUEST_FILTER_SUMMARY", "BARSREQUEST_UNEXPECTED_COUNT",
        "BARSREQUEST_ZERO_BARS_DIAGNOSTIC",
        
        // Pre-hydration
        "PRE_HYDRATION_BARS_LOADED", "PRE_HYDRATION_BARS_FILTERED",
        "PRE_HYDRATION_BARS_SKIPPED", "PRE_HYDRATION_BARS_SKIPPED_STREAM_STATE",
        "PRE_HYDRATION_BARS_SKIPPED_ACTIVE_STREAM", "PRE_HYDRATION_NO_BARS_AFTER_FILTER",
        "PRE_HYDRATION_WAITING_FOR_BARSREQUEST", "PRE_HYDRATION_COMPLETE_SET", "PRE_HYDRATION_COMPLETE_BLOCK_ENTERED",
        "PRE_HYDRATION_AFTER_COMPLETE_BLOCK", "PRE_HYDRATION_AFTER_VARIABLES",
        "PRE_HYDRATION_BEFORE_RANGE_DIAGNOSTIC", "PRE_HYDRATION_RANGE_START_DIAGNOSTIC",
        "PRE_HYDRATION_HANDLER_TRACE", "PRE_HYDRATION_FAILED",
        
        // Range computation
        "RANGE_LOCKED", "RANGE_COMPUTE_FAILED", "RANGE_COMPUTE_START",
        "RANGE_COMPUTE_NO_BARS_DIAGNOSTIC", "RANGE_COMPUTE_BAR_FILTERING",
        "RANGE_FIRST_BAR_ACCEPTED", "RANGE_INTENT_ASSERT", "RANGE_LOCK_ASSERT",
        "RANGE_INVALIDATED",
        
        // Gap detection
        "BAR_GAP_DETECTED", "GAP_TOLERANCE_VIOLATION", "GAP_TOLERATED",
        
        // Execution
        "EXECUTION_MODE_SET", "EXECUTION_BLOCKED", "EXECUTION_ERROR",         "EXECUTION_FILLED",
        "EXECUTION_PARTIAL_FILL", "EXECUTION_SKIPPED_DUPLICATE",         "EXECUTION_UPDATE_UNKNOWN_ORDER",
        "EXECUTION_UPDATE_ORDER_MAP_RETRY",
        "EXECUTION_UPDATE_SKIPPED_WRONG_INSTANCE", "EXECUTION_UPDATE_WRONG_INSTANCE_DIAGNOSTIC",
        "EXECUTION_UPDATE_GRACE_STARTED", "EXECUTION_UPDATE_GRACE_RETRY", "EXECUTION_UPDATE_GRACE_RESOLVED", "EXECUTION_UPDATE_GRACE_EXPIRED",
        "EXECUTION_DEFERRED_FOR_REGISTRY_RESOLUTION", "EXECUTION_DEFERRED_RETRY", "EXECUTION_DEFERRED_RESOLVED",
        "EXECUTION_DUPLICATE_DETECTED", "EXECUTION_DEDUP_SKIPPED", "EXECUTION_DEDUP_SKIPPED_PERMANENT", "ORDER_UPDATE_DEDUP_SKIPPED", "EXECUTION_RESOLUTION_TIMEOUT",
        "EXEC_ROUTER_ENDPOINT_REGISTERED", "EXEC_ROUTER_ENDPOINT_IDEMPOTENT", "EXEC_ROUTER_ENDPOINT_CONFLICT",
        "ENTRY_AGGREGATION_ATTEMPT", "ENTRY_AGGREGATION_SUCCESS", "ENTRY_AGGREGATION_FAILED",
        "AGG_ENTRY_FILL_ALLOCATED",
        "EXECUTION_UPDATE_MOCK", "EXECUTION_SUMMARY_WRITTEN", "EXECUTION_GATE_INVARIANT_VIOLATION",
        "BREAKOUT_DETECTED_ALREADY_ENTERED", "TRADE_COMPLETED",
        "ENTRY_BLOCKED_RISK", "RISK_CHECK_EVALUATED", "POSITION_FLATTEN_FAIL_CLOSED",
        "EXECUTION_FILL_UNMAPPED", "EXECUTION_GHOST_FILL_DETECTED", "PROTECTIVE_DRIFT_DETECTED",
        "ORPHAN_ORDER_DETECTED", "DUPLICATE_ORDER_SUBMISSION_DETECTED",         "POSITION_DRIFT_DETECTED",
        "EXPOSURE_INTEGRITY_VIOLATION",
        "ORDER_STUCK_DETECTED", "EXECUTION_LATENCY_SPIKE_DETECTED", "RECOVERY_LOOP_DETECTED",
        
        // Orders
        "ORDER_SUBMITTED", "ORDER_SUBMIT_SUCCESS", "ORDER_SUBMIT_FAIL", "ORDER_SUBMIT_ATTEMPT",
        "ORDER_ACKNOWLEDGED", "ORDER_REJECTED", "ORDER_CANCELLED", "OCO_SIBLING_CANCELLED", "ENTRY_SUBMITTED",
        "PROTECTIVES_PLACED", "PROTECTIVE_ORDERS_SUBMITTED", "PROTECTIVE_ORDERS_FAILED_FLATTENED",
        "STOP_BRACKETS_SUBMITTED", "STOP_BRACKETS_SUBMIT_ATTEMPT", "STOP_BRACKETS_SUBMIT_FAILED",
        "STOP_MODIFY_ATTEMPT", "STOP_MODIFY_SUCCESS", "STOP_MODIFY_REQUESTED", "STOP_MODIFY_CONFIRMED",
        "STOP_MODIFY_TIMEOUT", "STOP_MODIFY_FAILED", "STOP_MODIFY_FAILED_SNAPSHOT", "STOP_MODIFY_REJECTED", "STOP_MODIFY_PENDING_CLEARED_ON_EXIT",
        "ORDER_UPDATED", "BE_PREFLIGHT_STOP_ORDER_UPDATE",
        "STOP_MODIFY_FAIL", "STOP_MODIFY_SKIPPED", "BE_SKIP_STOP_ALREADY_TIGHTER",
        "BE_TRIGGER_REACHED", "BE_TRIGGER_RETRY_NEEDED", "BE_TRIGGER_FAILED", "BE_TRIGGER_TIMEOUT_ERROR",
        
        // Execution adapters
        "ADAPTER_SELECTED", "SIM_ACCOUNT_VERIFIED", "LIVE_MODE_BLOCKED",
        
        // Kill switch
        "KILL_SWITCH_INITIALIZED", "KILL_SWITCH_ACTIVE", "KILL_SWITCH_ERROR_FAIL_CLOSED",
        
        // Flatten
        "FLATTEN_ATTEMPT", "FLATTEN_SUCCESS", "FLATTEN_FAIL", "FLATTEN_FAILED_ALL_RETRIES", "FLATTEN_DRYRUN",
        
        // Recovery
        "DISCONNECT_FAIL_CLOSED_ENTERED", "DISCONNECT_RECOVERY_STARTED",
        "DISCONNECT_RECOVERY_COMPLETE", "DISCONNECT_RECOVERY_ABORTED",
        "DISCONNECT_RECOVERY_SKIPPED", "DISCONNECT_RECOVERY_WAITING_FOR_SYNC",
        "RECOVERY_ACCOUNT_SNAPSHOT", "RECOVERY_ACCOUNT_SNAPSHOT_FAILED",
        "RECOVERY_ACCOUNT_SNAPSHOT_NULL", "RECOVERY_CANCELLED_ROBOT_ORDERS",
        "RECOVERY_CANCELLED_ROBOT_ORDERS_FAILED", "RECOVERY_ORDERS_PRESERVED",
        "ENTRY_ORDERS_VERIFIED_PRESENT", "ENTRY_ORDERS_MISSING_DETECTED", "ENTRY_ORDERS_RESUBMITTED",
        "ENTRY_ORDERS_RESUBMIT_BLOCKED_POSITION_NOT_FLAT", "ENTRY_ORDERS_RESUBMIT_POSITION_CHECK_ERROR",
        "BREAKOUT_INVALIDATED", "ENTRY_RESUBMIT_BLOCKED_BREAKOUT",
        "RECOVERY_POSITION_RECONCILED",
        "RECOVERY_POSITION_UNMATCHED", "RECOVERY_PROTECTIVE_ORDERS_PLACED",
        "UNMATCHED_POSITION_POLICY_EVALUATION_STARTED", "UNMATCHED_POSITION_POLICY_CANDIDATE_FOUND", "UNMATCHED_POSITION_POLICY_NO_CANDIDATE",
        "UNMATCHED_POSITION_POLICY_ADOPT_APPROVED", "UNMATCHED_POSITION_POLICY_ADOPT_REJECTED",
        "UNMATCHED_POSITION_POLICY_FLATTEN_TRIGGERED", "UNMATCHED_POSITION_POLICY_ADOPT_COMPLETED",
        "UNMATCHED_POSITION_FLATTEN_RESULT",
        "RECOVERY_STREAM_ORDERS_RECONCILED",
        "PROTECTIVE_ORDERS_QUEUED_RECOVERY", "PROTECTIVE_ORDERS_SUBMITTED_FROM_RECOVERY_QUEUE",
        "RECOVERY_PROTECTIVE_TIMEOUT_FLATTENED",
        
        // Health monitoring
        "CONNECTION_LOST", "CONNECTION_LOST_SUSTAINED", "CONNECTION_CONTEXT", "CONNECTION_RECOVERED", "CONNECTION_RECOVERED_NOTIFICATION",
        "CONNECTIVITY_DAILY_SUMMARY", "CONNECTIVITY_INCIDENT", "CONNECTION_CONFIRMED",
        "DATA_LOSS_DETECTED", "DATA_STALL_RECOVERED",
        
        // Notifications
        "PUSHOVER_NOTIFY_ENQUEUED", "PUSHOVER_ENDPOINT",
        "CRITICAL_EVENT_REPORTED", "CRITICAL_NOTIFICATION_REJECTED", "CRITICAL_NOTIFICATION_SKIPPED", "CRITICAL_DEDUPE_MISSING_RUN_ID",
        "TEST_NOTIFICATION_SENT", "TEST_NOTIFICATION_SKIPPED", "TEST_NOTIFICATION_TRIGGER_ERROR",
        
        // Journal
        "JOURNAL_WRITTEN", "JOURNAL_INSTRUMENT_KEY_MISMATCH", "INTENT_EXECUTION_INSTRUMENT_MISSING", "EXECUTION_JOURNAL_ERROR", "EXECUTION_JOURNAL_READ_ERROR", "EXECUTION_JOURNAL_CORRUPTION", "EXECUTION_JOURNAL_ADOPTION_INDEX_REBUILT", "EXECUTION_JOURNAL_ADOPTION_INDEX_FALLBACK", "EXECUTION_JOURNAL_ADOPTION_INDEX_REBUILD_FAILED", "EXECUTION_SLIPPAGE_DETECTED",
        
        // Reconciliation
        "TRADE_RECONCILED", "RECONCILIATION_SKIPPED_HAS_WORKING_ORDERS", "RECONCILIATION_PASS_SUMMARY", "RECONCILIATION_QTY_MISMATCH", "RECONCILIATION_QTY_MISMATCH_STILL_OPEN", "RECONCILIATION_SECONDARY_INSTANCE_SKIPPED", "RECONCILIATION_RESOLVED", "RECONCILIATION_CONTEXT", "RECONCILIATION_ASSEMBLE_MISMATCH_DIAG",
        "RECONCILIATION_ORDER_SOURCE_BREAKDOWN",
        
        // Slot persistence
        "FORCED_FLATTEN_MARKET_CLOSE", "FORCED_FLATTEN_TRIGGERED", "FORCED_FLATTEN_POSITION_CLOSED", "FORCED_FLATTEN_ORDERS_CANCELLED",
        "FORCED_FLATTEN_FAILED", "FORCED_FLATTEN_RETRY", "FORCED_FLATTEN_EXPOSURE_REMAINING", "MANUAL_FLATTEN_REQUIRED", "FORCED_FLATTEN_ORDERS_CANCEL_ERROR", "FORCED_FLATTEN_VERIFY_ERROR",
        "SESSION_CLOSE_RESOLVED", "SESSION_CLOSE_RESOLUTION_SUCCESS", "SESSION_CLOSE_RESOLUTION_FAILURE", "SESSION_CLOSE_HOLIDAY",
        "SESSION_CLOSE_NO_ELIGIBLE_SEGMENTS", "SESSION_CLOSE_ITERATION_ERROR", "SESSION_CLOSE_EXCEPTION",
        "SESSION_CLOSE_RESOLVE_SKIPPED", "SESSION_CLOSE_FALLBACK_USED", "SESSION_CLOSE_CACHE_MISSING", "SESSION_CLOSE_FALLBACK_FAILED", "SESSION_CLOSE_RESOLVER_FAILED",
        "REENTRY_SUBMITTED", "REENTRY_FILLED",
        "REENTRY_PROTECTION_ACCEPTED", "REENTRY_FAILED", "REENTRY_PROTECTION_FAILED",
        "SLOT_EXPIRED", "SLOT_STATUS_CHANGED", "SLOT_FAILED_RUNTIME",
        
        // Intent exposure coordinator
        "INTENT_EXPOSURE_REGISTERED", "INTENT_EXPOSURE_CLOSED", "INTENT_EXIT_FILL", "INTENT_EXIT_FILL_NO_EXPOSURE",
        "INTENT_EXIT_VALIDATION_FAILED", "INTENT_PROTECTIVE_FAILURE", "INTENT_PROTECTIVE_FAILURE_FALLBACK",
        "BROKER_EXPOSURE_MISMATCH", "BROKER_EXPOSURE_RECALC_ERROR",
        "CANCEL_INTENT_ORDERS_BLOCKED", "CANCEL_INTENT_ORDERS_MOCK", "CANCEL_INTENT_ORDERS_SUCCESS", "CANCEL_INTENT_ORDERS_ERROR",
        "FLATTEN_INTENT_ATTEMPT", "FLATTEN_INTENT_SUCCESS", "FLATTEN_INTENT_ERROR",
        "FLATTEN_EMERGENCY_ON_BLOCK", "FLATTEN_EMERGENCY_ON_BLOCK_FAILED",
        "DUPLICATE_INSTANCE_DETECTED", "INTENT_POLICY_MISSING_AT_ORDER_CREATE",
        "INTENT_NOT_FOUND_FLATTEN_FAILED", "UNKNOWN_ORDER_FILL_FLATTEN_FAILED",
        "UNTRACKED_FILL_FLATTEN_FAILED",
        
        // Logging service
        "LOG_BACKPRESSURE_DROP", "LOG_PIPELINE_METRIC", "LOG_WORKER_LOOP_ERROR", "LOG_WRITE_FAILURE",
        "SNAPSHOT_METRICS",
        "LOG_HEALTH_ERROR", "LOG_CONVERSION_ERROR", "LOGGER_CONVERSION_ERROR", "LOGGER_CONVERSION_RETURNED_NULL",
        "LOGGING_INVARIANT_VIOLATION", "UNREGISTERED_EVENT_TYPE", "EXECUTION_EVENT_WRITE_FAILED",
        
        // Notification failures
        "NOTIFICATION_SEND_FAILED",
        
        // Account snapshots
        "ACCOUNT_SNAPSHOT_DRYRUN", "ACCOUNT_SNAPSHOT_ERROR", "ACCOUNT_SNAPSHOT_LIVE_ERROR",
        "ACCOUNT_SNAPSHOT_LIVE_STUB",
        
        // Order cancellation
        "CANCEL_ROBOT_ORDERS_DRYRUN", "CANCEL_ROBOT_ORDERS_ERROR",
        "CANCEL_ROBOT_ORDERS_LIVE_ERROR", "CANCEL_ROBOT_ORDERS_LIVE_STUB",
        "CANCEL_ROBOT_ORDERS_MOCK", "ROBOT_ORDERS_CANCELLED",
        
        // DRYRUN events
        "ENTRY_ORDER_DRYRUN", "STOP_ENTRY_ORDER_DRYRUN", "PROTECTIVE_STOP_DRYRUN",
        "TARGET_ORDER_DRYRUN", "BE_MODIFY_DRYRUN", "BE_PATH_ACTIVE", "BE_FILTER_EXCLUDED_ACTIVE_EXPOSURE", "ONMARKETDATA_LAST_DIAG",
        "BE_GATE_BLOCKED", "BE_ACCOUNT_EXPOSURE_WITHOUT_INTENT", "BE_INACTIVE_WHILE_EXPOSED",
        "BE_MODIFY_MAX_RETRIES_EXCEEDED", "BE_TICK_STALE_WARNING",
        "BE_TRIGGER_NEAR", "BE_MODIFY_FAILED", "BE_PRE_CHANGE_SNAPSHOT",
        "BE_RATE_LIMIT_SKIPPED", "BE_DEDUPE_SKIPPED", "BE_SCAN_THROTTLED",
        "BE_INTENTS_SCANNED", "BE_STRATEGY_THREAD_ENTERED",
        "BE_PROTECTION_STATE_CHANGED", "BE_PROTECTION_STATE_PRUNED", "PROTECTION_ENQUEUED_BACKLOG_WARN", "PROTECTION_ENQUEUED_BACKLOG_TIMEOUT", "BE_STOP_NOT_VISIBLE_PROTECTION_PENDING", "BE_STOP_VISIBILITY_TIMEOUT", "BE_STOP_VISIBILITY_TIMEOUT_SKIP_ACCOUNT_FLAT",
        "BE_TRIGGER_REACHED", "BE_TRIGGER_RETRY_NEEDED", "BE_TRIGGER_FAILED", "BE_TRIGGER_TIMEOUT_ERROR",
        
        // Tick/stream state
        "UPDATE_APPLIED",
        
        // Session
        "SESSION_START_TIME_SET",
        
        // Gaps
        "GAP_VIOLATIONS_SUMMARY",
        "PROTECTIVE_AUDIT_OK", "PROTECTIVE_AUDIT_FAILED", "PROTECTIVE_MISSING_STOP",
        "PROTECTIVE_STOP_QTY_MISMATCH", "PROTECTIVE_STOP_PRICE_INVALID",
        "PROTECTIVE_MISSING_TARGET", "PROTECTIVE_TARGET_QTY_MISMATCH",
        "PROTECTIVE_CONFLICTING_ORDERS", "PROTECTIVE_RECOVERY_STARTED",
        "PROTECTIVE_RECOVERY_SUBMITTED", "PROTECTIVE_RECOVERY_CONFIRMED",
        "PROTECTIVE_RECOVERY_FAILED", "PROTECTIVE_EMERGENCY_FLATTEN_TRIGGERED",
        "PROTECTIVE_INSTRUMENT_BLOCKED", "PROTECTIVE_AUDIT_METRICS",
        "RECONCILIATION_MISMATCH_DETECTED", "RECONCILIATION_MISMATCH_PERSISTENT",
        "RECONCILIATION_MISMATCH_FAIL_CLOSED", "RECONCILIATION_MISMATCH_CLEARED",
        "RECONCILIATION_MISMATCH_BLOCKED", "RECONCILIATION_MISMATCH_METRICS",
        "RECONCILIATION_PROGRESS_OBSERVED", "RECONCILIATION_NO_PROGRESS_DETECTED",
        "RECONCILIATION_THROTTLED", "RECONCILIATION_THROTTLE_RESET", "RECONCILIATION_THROTTLE_BACKOFF_UPDATED",
        "RECONCILIATION_HARD_STOPPED", "RECONCILIATION_EXECUTION_CAP_REACHED", "RECONCILIATION_REENTRY_BLOCKED",
        "STARTUP_RECOVERY_ADOPTION_OCCURRED",

        // Slot gate
        "SLOT_GATE_DIAGNOSTIC",
        
        // Operator
        "OPERATOR_BANNER",
        
        // Invariants
        "INVARIANT_VIOLATION", "STREAM_INSTRUMENT_INVARIANT_CHECK", "STREAM_INSTRUMENT_INVARIANT_MISMATCH",
        
        // Incident persistence
        "INCIDENT_PERSIST_ERROR",
        
        // Critical execution failures
        "FLATTEN_FAILED_ALL_RETRIES", "DUPLICATE_INSTANCE_DETECTED",
        "FLATTEN_REQUEST_RECEIVED", "FLATTEN_SKIPPED_ACCOUNT_FLAT", "FLATTEN_DIRECTION_INVALID",
        "FLATTEN_ABORTED_INVALID_POSITION_STATE", "FLATTEN_ALREADY_IN_PROGRESS", "FLATTEN_REQUEST_REJECTED_DUPLICATE",
        "FLATTEN_SENT", "FLATTEN_FILL_RECEIVED", "FLATTEN_RESOLVED", "FLATTEN_ORDER_REJECTED", "FLATTEN_LATCH_TIMEOUT",
        "ORDER_REGISTRY_REGISTERED", "ORDER_REGISTRY_FLATTEN_REGISTERED", "ORDER_REGISTRY_ADOPTED", "ORDER_REGISTRY_LIFECYCLE", "ORDER_REGISTRY_EXEC_RESOLVED",
        "UNOWNED_LIVE_ORDER_DETECTED", "ADOPTION_SCAN_START", "ADOPTION_SCAN_SUMMARY", "ADOPTION_DEFERRED_CANDIDATES_EMPTY", "ADOPTION_DEFERRAL_HEARTBEAT_RETRY",
        "ADOPTION_GRACE_EXPIRED_UNOWNED", "ADOPTION_CANDIDATES_EMPTY_NO_BROKER_ORDERS", "FOREIGN_INSTRUMENT_QTSW2_ORDER_SKIPPED",
        "ADOPTION_CANDIDATE_FOUND", "ADOPTION_CANDIDATE_NOT_FOUND", "STALE_QTSW2_ORDER_DETECTED", "ADOPTION_NON_CONVERGENCE_ESCALATED",
        "MANUAL_OR_EXTERNAL_ORDER_DETECTED", "ORDER_LIFECYCLE_TRANSITION_INVALID",
        "EXECUTION_UNOWNED", "REGISTRY_BROKER_DIVERGENCE", "REGISTRY_BROKER_DIVERGENCE_ADOPTED", "ORDER_REGISTRY_CLEANUP", "ORDER_REGISTRY_METRICS",
        "RECOVERY_STATE_TRANSITION_INVALID", "RECOVERY_TRIGGERED", "RECOVERY_REQUEST_RECEIVED", "RECOVERY_ALREADY_ACTIVE",
        "RECOVERY_ESCALATED", "RECOVERY_GUARD_BLOCKED_NORMAL_MANAGEMENT", "RECOVERY_RECONSTRUCTION_RESULT",
        "RECOVERY_RECONSTRUCTION_IGNORED", "RECOVERY_DECISION_RESUME", "RECOVERY_DECISION_ADOPT",
        "RECOVERY_DECISION_FLATTEN", "RECOVERY_DECISION_HALT", "RECOVERY_FLATTEN_REQUESTED", "RECOVERY_FLATTEN_RESOLVED",
        "RECOVERY_RESOLVED", "RECOVERY_HALTED", "RECOVERY_OPERATOR_ACTION_REQUIRED", "RECOVERY_METRICS",
        "RECOVERY_RECONSTRUCTION_ERROR",
        "BOOTSTRAP_STARTED", "BOOTSTRAP_ADOPTION_ATTEMPT", "BOOTSTRAP_ALREADY_ACTIVE", "BOOTSTRAP_SNAPSHOT_CAPTURED", "BOOTSTRAP_CLASSIFIED",
        "BOOTSTRAP_DECISION_RESUME", "BOOTSTRAP_DECISION_ADOPT", "BOOTSTRAP_DECISION_FLATTEN", "BOOTSTRAP_DECISION_HALT",
        "BOOTSTRAP_ADOPTION_COMPLETED", "BOOTSTRAP_READY_TO_RESUME", "BOOTSTRAP_HALTED", "BOOTSTRAP_OPERATOR_ACTION_REQUIRED",
        "BOOTSTRAP_SNAPSHOT_STALE", "BOOTSTRAP_SNAPSHOT_STALE_RERUN", "BOOTSTRAP_RESULT_IGNORED", "BOOTSTRAP_GUARD_BLOCKED_NORMAL_MANAGEMENT",
        "BOOTSTRAP_FORENSIC_CONTEXT_RECORDED", "BOOTSTRAP_METRICS", "CONNECTION_RECOVERY_REQUIRES_BOOTSTRAP", "CONNECTION_RECOVERY_RESOLVED",
        "SUPERVISORY_STATE_TRANSITION_INVALID", "SUPERVISORY_TRIGGERED", "SUPERVISORY_ESCALATED", "SUPERVISORY_ACTION_REQUESTED",
        "SUPERVISORY_ALREADY_ACTIVE", "SUPERVISORY_POLICY_APPLIED", "INSTRUMENT_COOLDOWN_STARTED", "INSTRUMENT_COOLDOWN_EXPIRED",
        "INSTRUMENT_SUSPENDED", "INSTRUMENT_HALTED", "INSTRUMENT_HALT_CLEARED", "OPERATOR_ACK_REQUIRED", "OPERATOR_ACK_RECEIVED", "OPERATOR_ACK_REJECTED",
        "INSTRUMENT_KILL_SWITCH_ACTIVATED", "GLOBAL_KILL_SWITCH_ACTIVATED", "GLOBAL_KILL_SWITCH_CLEARED",
        "SUPERVISORY_THRESHOLD_EXCEEDED", "SUPERVISORY_COOLDOWN_ESCALATED", "SUPERVISORY_HALT_ESCALATED",
        "SUPERVISORY_RESUME_ALLOWED", "SUPERVISORY_RESUME_BLOCKED", "SUPERVISORY_METRICS",
        "INTENT_POLICY_MISSING_AT_ORDER_CREATE", "INTENT_NOT_FOUND_FLATTEN_FAILED",
        "UNKNOWN_ORDER_FILL_FLATTEN_FAILED", "UNTRACKED_FILL_FLATTEN_FAILED",
        "EXECUTION_COMMAND_STALLED", "EXECUTION_QUEUE_POISON_DETECTED",
        "IEA_QUEUE_PRESSURE_DIAG", "IEA_EXPENSIVE_PATH_THREAD",
        "IEA_ADOPTION_SCAN_REQUEST_ACCEPTED", "IEA_ADOPTION_SCAN_REQUEST_SKIPPED", "IEA_ADOPTION_SCAN_EXECUTION_STARTED", "IEA_ADOPTION_SCAN_EXECUTION_COMPLETED",
        "IEA_ADOPTION_SCAN_GATE_ANOMALY", "IEA_ADOPTION_SCAN_OFF_WORKER_VIOLATION",
        "IEA_ADOPTION_SCAN_SKIPPED_NO_PROGRESS",
        "IEA_ADOPTION_SCAN_NO_PROGRESS_NOT_SKIPPED",
        "IEA_ADOPTION_SCAN_MUTATION_TIME_ALIGNED",
        "IEA_ADOPTION_SCAN_PHASE_TIMING",
        "IEA_VERIFY_REGISTRY_INTEGRITY_DIAG", "ADOPTION_SAME_STATE_RETRY_WINDOW",
    };
}
