// SINGLE SOURCE OF TRUTH
// This file is the authoritative registry of all robot event types.
// It is compiled into Robot.Core.dll and should be referenced from that DLL.
// Do not duplicate this file elsewhere - if source is needed, reference Robot.Core.dll instead.
//
// Linked into: Robot.Core.csproj (modules/robot/core/)
// Referenced by: RobotCore_For_NinjaTrader (via Robot.Core.dll)

using System;
using System.Collections.Generic;

namespace QTSW2.Robot.Core;

/// <summary>
/// Centralized registry of all robot event types with level assignments.
/// This provides compile-time validation and consistent level assignment.
/// </summary>
public static class RobotEventTypes
{
    /// <summary>
    /// Get the log level for an event type.
    /// Returns "INFO" if event type is unknown (fail-safe).
    /// </summary>
    public static string GetLevel(string eventType)
    {
        if (string.IsNullOrWhiteSpace(eventType))
            return "INFO";
        
        if (_levelMap.TryGetValue(eventType, out var level))
            return level;
        
        // Fallback: use heuristics for unknown events
        var upper = eventType.ToUpperInvariant();
        if (upper.Contains("CRITICAL") || upper.Contains("KILL_SWITCH") || upper.Contains("FLATTEN_FAILED_ALL") ||
            upper.Contains("DUPLICATE_INSTANCE") || upper.Contains("FLATTEN_FAILED"))
            return "CRITICAL";
        if (upper.Contains("ERROR") || upper.Contains("FAIL") || upper.Contains("INVALID") || upper.Contains("VIOLATION"))
            return "ERROR";
        if (upper.Contains("WARN") || upper.Contains("BLOCKED"))
            return "WARN";
        if (upper.Contains("DEBUG") || upper.Contains("DIAGNOSTIC") || upper.Contains("TRACE") || upper.Contains("HEARTBEAT"))
            return "DEBUG";
        
        return "INFO";
    }
    
    /// <summary>
    /// Check if an event type is valid (exists in registry).
    /// </summary>
    public static bool IsValid(string eventType)
    {
        if (string.IsNullOrWhiteSpace(eventType))
            return false;
        
        return _levelMap.ContainsKey(eventType) || _allEvents.Contains(eventType);
    }
    
    /// <summary>
    /// Get all registered event types.
    /// </summary>
    public static IEnumerable<string> GetAllEventTypes()
    {
        return _allEvents;
    }
    
    // Level mapping: event type -> log level
    private static readonly Dictionary<string, string> _levelMap = new(StringComparer.OrdinalIgnoreCase)
    {
        // Engine lifecycle
        ["ENGINE_START"] = "INFO",
        ["STARTUP_DEPENDENCY_CHECK_FAILED"] = "ERROR",
        ["ROBOT_BUILD_SIGNATURE"] = "INFO",
        ["ENGINE_STOP"] = "INFO",
        ["ENGINE_STAND_DOWN"] = "WARN",
        ["ENGINE_TICK_INVALID_STATE"] = "ERROR",
        ["ENGINE_TICK_STALL_DETECTED"] = "ERROR",
        ["ENGINE_TICK_STALL_STARTUP"] = "INFO",
        ["ENGINE_TICK_STALL_RUNTIME"] = "ERROR",
        ["ENGINE_TICK_STALL_RECOVERED"] = "INFO",
        ["ENGINE_TICK_CALLSITE"] = "WARN",  // Watchdog liveness - never drop under backpressure
        ["ENGINE_TIMER_HEARTBEAT"] = "INFO",  // Timer-based heartbeat when market closed (no ticks)

        // Timer diagnostics
        ["TIMER_LIFECYCLE_STATE_TRANSITION"] = "INFO",
        ["TIMER_LIFECYCLE_START_ATTEMPT"] = "INFO",
        ["TIMER_LIFECYCLE_START_SKIPPED"] = "INFO",
        ["TIMER_LIFECYCLE_STARTED"] = "INFO",
        ["TIMER_LIFECYCLE_ERROR"] = "ERROR",
        ["TIMER_GATE_EARLY_RETURN"] = "WARN",
        ["TIMER_META_HEARTBEAT"] = "INFO",
        ["TIMER_CALLBACK_EXCEPTION"] = "ERROR",
        
        // Configuration
        ["PROJECT_ROOT_RESOLVED"] = "INFO",
        ["LOG_DIR_RESOLVED"] = "INFO",
        ["LOGGING_CONFIG_LOADED"] = "INFO",
        ["LOGGING_CONFIG_LOAD_FAILED"] = "ERROR",
        ["SPEC_LOADED"] = "INFO",
        ["SPEC_INVALID"] = "ERROR",
        ["SPEC_NAME_LOADED"] = "INFO",
        ["HEALTH_MONITOR_CONFIG_LOADED"] = "INFO",
        ["HEALTH_MONITOR_CONFIG_ERROR"] = "ERROR",
        ["HEALTH_MONITOR_CONFIG_MISSING"] = "WARN",
        ["HEALTH_MONITOR_CONFIG_NULL"] = "WARN",
        ["HEALTH_MONITOR_DISABLED"] = "INFO",
        ["HEALTH_MONITOR_STARTED"] = "INFO",
        ["HEALTH_MONITOR_EVALUATION_ERROR"] = "ERROR",
        ["PUSHOVER_CONFIG_MISSING"] = "WARN",
        
        // Timetable
        ["TIMETABLE_LOADED"] = "INFO",
        ["TIMETABLE_UPDATED"] = "INFO",
        ["TIMETABLE_VALIDATED"] = "INFO",
        ["TIMETABLE_INVALID"] = "ERROR",
        ["TIMETABLE_INVALID_TRADING_DATE"] = "ERROR",
        ["TIMETABLE_MISSING_TRADING_DATE"] = "ERROR",
        ["TIMETABLE_TRADING_DATE_MISMATCH"] = "ERROR",
        ["TIMETABLE_APPLY_SKIPPED"] = "INFO",
        ["TIMETABLE_PARSING_COMPLETE"] = "INFO",
        ["TIMETABLE_POLL_STALL_DETECTED"] = "ERROR",
        ["TIMETABLE_POLL_STALL_RECOVERED"] = "INFO",
        
        // Trading date
        ["TRADING_DATE_LOCKED"] = "INFO",
        
        // Streams
        ["STREAMS_CREATED"] = "INFO",
        ["STREAMS_CREATION_FAILED"] = "ERROR",
        ["STREAMS_CREATION_SKIPPED"] = "WARN",
        ["DUPLICATE_STREAM_ID"] = "ERROR",
        ["STREAM_STAND_DOWN"] = "WARN",
        ["STREAM_SKIPPED"] = "INFO",
        
        // Bars
        ["BAR_ACCEPTED"] = "DEBUG",
        ["BAR_DATE_MISMATCH"] = "WARN",
        ["BAR_PARTIAL_REJECTED"] = "WARN",
        ["BAR_RECEIVED_BEFORE_DATE_LOCKED"] = "WARN",
        ["BAR_RECEIVED_NO_STREAMS"] = "WARN",
        ["BAR_REJECTION_CONTINUOUS_FUTURE"] = "WARN",
        ["BAR_REJECTION_CONTINUOUS_NO_DATE_LOCK"] = "WARN",
        ["BAR_REJECTION_RATE_HIGH"] = "WARN",
        ["BAR_REJECTION_SUMMARY"] = "INFO",
        ["BAR_DELIVERY_SUMMARY"] = "INFO",
        ["BAR_DELIVERY_TO_STREAM"] = "DEBUG",
        ["BAR_ROUTING_DIAGNOSTIC"] = "DEBUG",
        ["BAR_TIME_INTERPRETATION_MISMATCH"] = "WARN",
        ["BAR_TIME_INTERPRETATION_LOCKED"] = "INFO",
        ["BAR_TIME_DETECTION_STARTING"] = "DEBUG",
        ["BAR_FLOW_STALLED"] = "WARN",
        
        // BarsRequest
        ["BARSREQUEST_REQUESTED"] = "INFO",
        ["BARSREQUEST_EXECUTED"] = "INFO",
        ["BARSREQUEST_FAILED"] = "ERROR",
        ["BARSREQUEST_SKIPPED"] = "INFO",
        ["BARSREQUEST_INITIALIZATION"] = "INFO",
        ["BARSREQUEST_RANGE_CHECK"] = "DEBUG",
        ["BARSREQUEST_RANGE_DETERMINED"] = "INFO",
        ["BARSREQUEST_STREAM_STATUS"] = "DEBUG",
        ["BARSREQUEST_FILTER_SUMMARY"] = "DEBUG",
        ["BARSREQUEST_UNEXPECTED_COUNT"] = "WARN",
        ["BARSREQUEST_ZERO_BARS_DIAGNOSTIC"] = "DEBUG",
        
        // Pre-hydration
        ["PRE_HYDRATION_BARS_LOADED"] = "INFO",
        ["PRE_HYDRATION_BARS_FILTERED"] = "DEBUG",
        ["PRE_HYDRATION_BARS_SKIPPED"] = "DEBUG",
        ["PRE_HYDRATION_BARS_SKIPPED_STREAM_STATE"] = "DEBUG",
        ["PRE_HYDRATION_BARS_SKIPPED_ACTIVE_STREAM"] = "DEBUG",
        ["PRE_HYDRATION_NO_BARS_AFTER_FILTER"] = "WARN",
        ["PRE_HYDRATION_WAITING_FOR_BARSREQUEST"] = "DEBUG",
        ["PRE_HYDRATION_COMPLETE_SET"] = "DEBUG",
        ["PRE_HYDRATION_COMPLETE_BLOCK_ENTERED"] = "DEBUG",
        ["PRE_HYDRATION_AFTER_COMPLETE_BLOCK"] = "DEBUG",
        ["PRE_HYDRATION_AFTER_VARIABLES"] = "DEBUG",
        ["PRE_HYDRATION_BEFORE_RANGE_DIAGNOSTIC"] = "DEBUG",
        ["PRE_HYDRATION_RANGE_START_DIAGNOSTIC"] = "DEBUG",
        ["PRE_HYDRATION_HANDLER_TRACE"] = "DEBUG",
        ["PRE_HYDRATION_FAILED"] = "ERROR",
        
        // Range computation
        ["RANGE_LOCKED"] = "INFO",
        ["RANGE_COMPUTE_FAILED"] = "ERROR",
        ["RANGE_COMPUTE_START"] = "DEBUG",
        ["RANGE_COMPUTE_NO_BARS_DIAGNOSTIC"] = "DEBUG",
        ["RANGE_COMPUTE_BAR_FILTERING"] = "DEBUG",
        ["RANGE_FIRST_BAR_ACCEPTED"] = "DEBUG",
        ["RANGE_INTENT_ASSERT"] = "DEBUG",
        ["RANGE_LOCK_ASSERT"] = "DEBUG",
        ["RANGE_INVALIDATED"] = "WARN",
        
        // Gap detection
        ["BAR_GAP_DETECTED"] = "DEBUG",
        ["GAP_TOLERANCE_VIOLATION"] = "ERROR",
        ["GAP_TOLERATED"] = "WARN",
        
        // Execution
        ["EXECUTION_MODE_SET"] = "INFO",
        ["EXECUTION_BLOCKED"] = "WARN",
        ["EXECUTION_ERROR"] = "ERROR",
        ["EXECUTION_FILLED"] = "INFO",
        ["EXECUTION_PARTIAL_FILL"] = "INFO",
        ["ENTRY_AGGREGATION_ATTEMPT"] = "DEBUG",
        ["ENTRY_AGGREGATION_SUCCESS"] = "INFO",
        ["ENTRY_AGGREGATION_FAILED"] = "ERROR",
        ["AGG_ENTRY_FILL_ALLOCATED"] = "INFO",
        ["EXECUTION_SKIPPED_DUPLICATE"] = "WARN",
        ["EXECUTION_UPDATE_UNKNOWN_ORDER"] = "WARN",
        ["EXECUTION_UPDATE_ORDER_MAP_RETRY"] = "DEBUG",
        ["EXECUTION_UPDATE_SKIPPED_WRONG_INSTANCE"] = "DEBUG",
        ["EXECUTION_UPDATE_WRONG_INSTANCE_DIAGNOSTIC"] = "DEBUG",
        ["EXECUTION_UPDATE_MOCK"] = "DEBUG",
        ["EXECUTION_SUMMARY_WRITTEN"] = "INFO",
        ["EXECUTION_GATE_INVARIANT_VIOLATION"] = "ERROR",
        ["BREAKOUT_DETECTED_ALREADY_ENTERED"] = "WARN",
        ["TRADE_COMPLETED"] = "INFO",
        ["COMPLETED_INTENT_RECEIVED_FILL"] = "CRITICAL",
        ["TERMINAL_INTENT_HAS_WORKING_ORDERS"] = "CRITICAL",
        ["TERMINAL_INTENT_VERIFIED"] = "INFO",
        ["COMPLETED_INTENT_ORDER_UPDATE"] = "WARN",
        ["ENTRY_BLOCKED_RISK"] = "WARN",
        ["RISK_CHECK_EVALUATED"] = "DEBUG",
        ["POSITION_FLATTEN_FAIL_CLOSED"] = "CRITICAL",
        
        // Orders
        ["ORDER_SUBMITTED"] = "INFO",
        ["ORDER_SUBMIT_SUCCESS"] = "INFO",
        ["ORDER_SUBMIT_FAIL"] = "ERROR",
        ["ORDER_SUBMIT_ATTEMPT"] = "DEBUG",
        ["ORDER_ACKNOWLEDGED"] = "INFO",
        ["ORDER_REJECTED"] = "ERROR",
        ["ORDER_CANCELLED"] = "INFO",
        ["OCO_SIBLING_CANCELLED"] = "INFO",
        ["ENTRY_SUBMITTED"] = "INFO",
        ["PROTECTIVES_PLACED"] = "INFO",
        ["PROTECTIVE_ORDERS_SUBMITTED"] = "INFO",
        ["PROTECTIVE_ORDERS_FAILED_FLATTENED"] = "WARN",
        ["STOP_BRACKETS_SUBMITTED"] = "INFO",
        ["STOP_BRACKETS_SUBMIT_ATTEMPT"] = "DEBUG",
        ["STOP_BRACKETS_SUBMIT_FAILED"] = "ERROR",
        ["STOP_MODIFY_ATTEMPT"] = "DEBUG",
        ["STOP_MODIFY_SUCCESS"] = "INFO",
        ["STOP_MODIFY_REQUESTED"] = "INFO",
        ["STOP_MODIFY_CONFIRMED"] = "INFO",
        ["STOP_MODIFY_TIMEOUT"] = "WARN",
        ["STOP_MODIFY_FAILED"] = "ERROR",
        ["STOP_MODIFY_FAILED_SNAPSHOT"] = "DEBUG",
        ["STOP_MODIFY_REJECTED"] = "WARN",
        ["STOP_MODIFY_PENDING_CLEARED_ON_EXIT"] = "INFO",
        ["ORDER_UPDATED"] = "INFO",
        ["BE_PREFLIGHT_STOP_ORDER_UPDATE"] = "DEBUG",
        ["STOP_MODIFY_FAIL"] = "ERROR",
        ["STOP_MODIFY_SKIPPED"] = "DEBUG",
        ["BE_SKIP_STOP_ALREADY_TIGHTER"] = "DEBUG",
        ["BE_TRIGGER_REACHED"] = "INFO",
        ["BE_TRIGGER_RETRY_NEEDED"] = "INFO",
        ["BE_TRIGGER_FAILED"] = "WARN",
        ["BE_TRIGGER_TIMEOUT_ERROR"] = "ERROR",
        
        // Execution adapters
        ["ADAPTER_SELECTED"] = "INFO",
        ["SIM_ACCOUNT_VERIFIED"] = "INFO",
        ["LIVE_MODE_BLOCKED"] = "ERROR",
        
        // IEA (Instrument Execution Authority)
        ["IEA_BINDING"] = "INFO",
        ["IEA_HEARTBEAT"] = "DEBUG",
        ["IEA_EXEC_UPDATE_ROUTED"] = "INFO",
        ["IEA_ENQUEUE_AND_WAIT_TIMEOUT"] = "CRITICAL",
        ["IEA_ENQUEUE_AND_WAIT_QUEUE_OVERFLOW"] = "CRITICAL",
        ["IEA_ENQUEUE_REJECTED_INSTRUMENT_BLOCKED"] = "WARN",
        ["IEA_QUEUE_WORKER_ERROR"] = "ERROR",
        ["IEA_ENQUEUE_FAILURE_INSTRUMENT_BLOCKED"] = "CRITICAL",
        ["IEA_BYPASS_ATTEMPTED"] = "ERROR",
        ["EXECUTION_COMMAND_STALLED"] = "CRITICAL",
        ["EXECUTION_QUEUE_POISON_DETECTED"] = "CRITICAL",
        
        // Kill switch
        ["KILL_SWITCH_INITIALIZED"] = "INFO",
        ["KILL_SWITCH_ACTIVE"] = "CRITICAL",
        ["KILL_SWITCH_ERROR_FAIL_CLOSED"] = "CRITICAL",
        
        // Flatten
        ["FLATTEN_ATTEMPT"] = "INFO",
        ["FLATTEN_SUCCESS"] = "INFO",
        ["FLATTEN_FAIL"] = "ERROR",
        ["FLATTEN_FAILED_ALL_RETRIES"] = "CRITICAL",
        ["FLATTEN_DRYRUN"] = "DEBUG",
        
        // Recovery
        ["DISCONNECT_FAIL_CLOSED_ENTERED"] = "ERROR",
        ["DISCONNECT_RECOVERY_STARTED"] = "INFO",
        ["DISCONNECT_RECOVERY_COMPLETE"] = "INFO",
        ["DISCONNECT_RECOVERY_ABORTED"] = "WARN",
        ["DISCONNECT_RECOVERY_SKIPPED"] = "INFO",
        ["DISCONNECT_RECOVERY_WAITING_FOR_SYNC"] = "INFO",
        ["RECOVERY_ACCOUNT_SNAPSHOT"] = "INFO",
        ["RECOVERY_ACCOUNT_SNAPSHOT_FAILED"] = "ERROR",
        ["RECOVERY_ACCOUNT_SNAPSHOT_NULL"] = "WARN",
        ["RECOVERY_CANCELLED_ROBOT_ORDERS"] = "INFO",
        ["RECOVERY_CANCELLED_ROBOT_ORDERS_FAILED"] = "ERROR",
        ["RECOVERY_POSITION_RECONCILED"] = "INFO",
        ["RECOVERY_POSITION_UNMATCHED"] = "WARN",
        ["UNMATCHED_POSITION_POLICY_EVALUATION_STARTED"] = "INFO",
        ["UNMATCHED_POSITION_POLICY_CANDIDATE_FOUND"] = "INFO",
        ["UNMATCHED_POSITION_POLICY_NO_CANDIDATE"] = "WARN",
        ["UNMATCHED_POSITION_POLICY_ADOPT_APPROVED"] = "INFO",
        ["UNMATCHED_POSITION_POLICY_ADOPT_REJECTED"] = "WARN",
        ["UNMATCHED_POSITION_POLICY_FLATTEN_TRIGGERED"] = "WARN",
        ["UNMATCHED_POSITION_POLICY_ADOPT_COMPLETED"] = "INFO",
        ["UNMATCHED_POSITION_FLATTEN_RESULT"] = "INFO",
        ["RECOVERY_PROTECTIVE_ORDERS_PLACED"] = "INFO",
        ["RECOVERY_STREAM_ORDERS_RECONCILED"] = "INFO",
        ["RECOVERY_ORDERS_PRESERVED"] = "INFO",
        ["ENTRY_ORDERS_VERIFIED_PRESENT"] = "INFO",
        ["ENTRY_ORDERS_MISSING_DETECTED"] = "WARN",
        ["ENTRY_ORDERS_RESUBMITTED"] = "INFO",
        ["ENTRY_ORDERS_RESUBMIT_BLOCKED_POSITION_NOT_FLAT"] = "WARN",
        ["ENTRY_ORDERS_RESUBMIT_POSITION_CHECK_ERROR"] = "ERROR",
        ["RECOVERY_SECOND_RECONCILIATION"] = "INFO",
        ["RECOVERY_SECOND_RECONCILIATION_ERROR"] = "WARN",
        ["ENTRY_ORDER_SET_VALID"] = "INFO",
        ["ENTRY_ORDER_SET_MISSING"] = "WARN",
        ["ENTRY_ORDER_SET_BROKEN"] = "WARN",
        ["ENTRY_ORDER_SET_DUPLICATE_DETECTED"] = "WARN",
        ["ENTRY_ORDER_SET_CANCEL_REQUESTED"] = "INFO",
        ["ENTRY_ORDER_SET_CANCEL_CONFIRMED"] = "INFO",
        ["ENTRY_ORDER_SET_REBUILD_REQUESTED"] = "INFO",
        ["ENTRY_ORDER_SET_RESUBMIT_SKIPPED_POSITION_EXISTS"] = "WARN",
        ["ENTRY_ORDER_SET_RESUBMIT_SKIPPED_VALID_EXISTS"] = "INFO",
        ["ENTRY_ORDER_SET_REBUILD_BLOCKED_CANCEL_INCOMPLETE"] = "WARN",
        ["ENTRY_ORDER_ACTION_CLEARED_STREAM_INELIGIBLE"] = "INFO",
        ["ENTRY_ORDER_INVARIANT_VIOLATED"] = "ERROR",
        ["ENTRY_ORDER_RESUBMIT_SKIPPED_BREAKOUT_ALREADY_TRIGGERED"] = "WARN",
        ["BREAKOUT_INVALIDATED"] = "WARN",
        ["ENTRY_RESUBMIT_BLOCKED_BREAKOUT"] = "WARN",
        
        // Health monitoring
        ["CONNECTION_LOST"] = "ERROR",
        ["CONNECTION_LOST_SUSTAINED"] = "ERROR",
        ["CONNECTION_CONTEXT"] = "INFO",
        ["CONNECTION_RECOVERED"] = "INFO",
        ["CONNECTION_RECOVERED_NOTIFICATION"] = "INFO",
        ["CONNECTION_CONFIRMED"] = "INFO",
        ["DATA_LOSS_DETECTED"] = "ERROR",
        ["DATA_STALL_RECOVERED"] = "INFO",
        
        // Notifications
        ["PUSHOVER_NOTIFY_ENQUEUED"] = "DEBUG",
        ["PUSHOVER_ENDPOINT"] = "DEBUG",
        ["CRITICAL_EVENT_REPORTED"] = "INFO",
        ["CRITICAL_NOTIFICATION_REJECTED"] = "WARN",
        ["CRITICAL_NOTIFICATION_SKIPPED"] = "WARN",
        ["CRITICAL_DEDUPE_MISSING_RUN_ID"] = "WARN",
        ["TEST_NOTIFICATION_SENT"] = "INFO",
        ["TEST_NOTIFICATION_SKIPPED"] = "WARN",
        ["TEST_NOTIFICATION_TRIGGER_ERROR"] = "ERROR",
        
        // Journal
        ["JOURNAL_WRITTEN"] = "DEBUG",
        ["EXECUTION_JOURNAL_ERROR"] = "ERROR",
        ["EXECUTION_JOURNAL_READ_ERROR"] = "ERROR",
        ["EXECUTION_JOURNAL_CORRUPTION"] = "ERROR",
        ["EXECUTION_SLIPPAGE_DETECTED"] = "INFO",
        
        // Reconciliation
        ["TRADE_RECONCILED"] = "INFO",
        ["RECONCILIATION_SKIPPED_HAS_WORKING_ORDERS"] = "INFO",
        ["RECONCILIATION_PASS_SUMMARY"] = "INFO",
        ["RECONCILIATION_QTY_MISMATCH"] = "CRITICAL",
        ["RECONCILIATION_CONTEXT"] = "INFO",
        ["RECONCILIATION_ORDER_SOURCE_BREAKDOWN"] = "INFO",
        
        // Slot persistence
        ["FORCED_FLATTEN_MARKET_CLOSE"] = "WARN",
        ["FORCED_FLATTEN_TRIGGERED"] = "INFO",
        ["FORCED_FLATTEN_SKIP_NO_CACHE"] = "WARN",
        ["FORCED_FLATTEN_POSITION_CLOSED"] = "INFO",
        ["FORCED_FLATTEN_ORDERS_CANCELLED"] = "INFO",
        ["FORCED_FLATTEN_FAILED"] = "CRITICAL",
        ["FORCED_FLATTEN_RETRY"] = "WARN",
        ["FORCED_FLATTEN_EXPOSURE_REMAINING"] = "CRITICAL",
        ["MANUAL_FLATTEN_REQUIRED"] = "CRITICAL",
        ["FORCED_FLATTEN_ORDERS_CANCEL_ERROR"] = "ERROR",
        ["FORCED_FLATTEN_VERIFY_ERROR"] = "WARN",
        ["SESSION_CLOSE_RESOLVED"] = "INFO",
        ["SESSION_CLOSE_HOLIDAY"] = "INFO",
        ["SESSION_CLOSE_FALLBACK_USED"] = "WARN",
        ["SESSION_CLOSE_FALLBACK_FAILED"] = "CRITICAL",
        ["SESSION_CLOSE_CACHE_MISSING"] = "ERROR",
        ["REENTRY_SUBMITTED"] = "INFO",
        ["REENTRY_FILLED"] = "INFO",
        ["REENTRY_PROTECTION_ACCEPTED"] = "INFO",
        ["REENTRY_FAILED"] = "ERROR",
        ["REENTRY_PROTECTION_FAILED"] = "ERROR",
        ["SLOT_EXPIRED"] = "INFO",
        ["SLOT_STATUS_CHANGED"] = "INFO",
        ["SLOT_FAILED_RUNTIME"] = "ERROR",
        
        // Intent exposure coordinator
        ["INTENT_EXPOSURE_REGISTERED"] = "INFO",
        ["INTENT_EXPOSURE_CLOSED"] = "INFO",
        ["INTENT_EXIT_FILL"] = "INFO",
        ["INTENT_EXIT_FILL_NO_EXPOSURE"] = "WARN",
        ["INTENT_EXIT_VALIDATION_FAILED"] = "WARN",
        ["INTENT_PROTECTIVE_FAILURE"] = "ERROR",
        ["INTENT_PROTECTIVE_FAILURE_FALLBACK"] = "ERROR",
        ["BROKER_EXPOSURE_MISMATCH"] = "WARN",
        ["BROKER_EXPOSURE_RECALC_ERROR"] = "WARN",
        ["CANCEL_INTENT_ORDERS_BLOCKED"] = "WARN",
        ["CANCEL_INTENT_ORDERS_MOCK"] = "INFO",
        ["CANCEL_INTENT_ORDERS_SUCCESS"] = "INFO",
        ["CANCEL_INTENT_ORDERS_ERROR"] = "ERROR",
        ["FLATTEN_INTENT_ATTEMPT"] = "INFO",
        ["FLATTEN_INTENT_SUCCESS"] = "INFO",
        ["FLATTEN_INTENT_ERROR"] = "ERROR",
        ["FLATTEN_EMERGENCY_ON_BLOCK"] = "INFO",
        ["FLATTEN_EMERGENCY_ON_BLOCK_FAILED"] = "ERROR",
        
        // Logging service
        ["LOG_BACKPRESSURE_DROP"] = "ERROR",
        ["LOG_PIPELINE_METRIC"] = "INFO",
        ["LOG_WORKER_LOOP_ERROR"] = "ERROR",
        ["LOG_WRITE_FAILURE"] = "ERROR",
        ["LOG_HEALTH_ERROR"] = "ERROR",
        ["LOG_CONVERSION_ERROR"] = "ERROR",
        ["LOGGER_CONVERSION_ERROR"] = "ERROR",
        ["LOGGER_CONVERSION_RETURNED_NULL"] = "ERROR",
        ["LOGGING_INVARIANT_VIOLATION"] = "ERROR",
        ["EXECUTION_EVENT_WRITE_FAILED"] = "ERROR",
        ["UNREGISTERED_EVENT_TYPE"] = "WARN",
        
        // Notification failures
        ["NOTIFICATION_SEND_FAILED"] = "ERROR",
        
        // Account snapshots
        ["ACCOUNT_SNAPSHOT_DRYRUN"] = "DEBUG",
        ["ACCOUNT_SNAPSHOT_ERROR"] = "ERROR",
        ["ACCOUNT_SNAPSHOT_LIVE_ERROR"] = "ERROR",
        ["ACCOUNT_SNAPSHOT_LIVE_STUB"] = "DEBUG",
        
        // Order cancellation
        ["CANCEL_ROBOT_ORDERS_DRYRUN"] = "DEBUG",
        ["CANCEL_ROBOT_ORDERS_ERROR"] = "ERROR",
        ["CANCEL_ROBOT_ORDERS_LIVE_ERROR"] = "ERROR",
        ["CANCEL_ROBOT_ORDERS_LIVE_STUB"] = "DEBUG",
        ["CANCEL_ROBOT_ORDERS_MOCK"] = "DEBUG",
        ["ROBOT_ORDERS_CANCELLED"] = "INFO",
        
        // DRYRUN events
        ["ENTRY_ORDER_DRYRUN"] = "DEBUG",
        ["STOP_ENTRY_ORDER_DRYRUN"] = "DEBUG",
        ["PROTECTIVE_STOP_DRYRUN"] = "DEBUG",
        ["TARGET_ORDER_DRYRUN"] = "DEBUG",
        ["BE_MODIFY_DRYRUN"] = "DEBUG",
        ["BE_PATH_ACTIVE"] = "INFO",
        ["BE_FILTER_EXCLUDED_ACTIVE_EXPOSURE"] = "CRITICAL",
        ["ONMARKETDATA_LAST_DIAG"] = "INFO",
        ["BE_GATE_BLOCKED"] = "WARN",
        ["BE_ACCOUNT_EXPOSURE_WITHOUT_INTENT"] = "WARN",
        ["BE_INACTIVE_WHILE_EXPOSED"] = "WARN",
        ["BE_MODIFY_MAX_RETRIES_EXCEEDED"] = "CRITICAL",
        ["BE_TICK_STALE_WARNING"] = "WARN",
        
        // Tick/stream state
        ["UPDATE_APPLIED"] = "DEBUG",
        
        // Session
        ["SESSION_START_TIME_SET"] = "INFO",
        
        // Gaps
        ["GAP_VIOLATIONS_SUMMARY"] = "WARN",

        // Protective coverage audit (Gap 3)
        ["PROTECTIVE_AUDIT_OK"] = "DEBUG",
        ["PROTECTIVE_AUDIT_FAILED"] = "ERROR",
        ["PROTECTIVE_MISSING_STOP"] = "CRITICAL",
        ["PROTECTIVE_STOP_QTY_MISMATCH"] = "CRITICAL",
        ["PROTECTIVE_STOP_PRICE_INVALID"] = "CRITICAL",
        ["PROTECTIVE_MISSING_TARGET"] = "WARN",
        ["PROTECTIVE_TARGET_QTY_MISMATCH"] = "WARN",
        ["PROTECTIVE_CONFLICTING_ORDERS"] = "CRITICAL",
        ["PROTECTIVE_RECOVERY_STARTED"] = "INFO",
        ["PROTECTIVE_RECOVERY_SUBMITTED"] = "INFO",
        ["PROTECTIVE_RECOVERY_CONFIRMED"] = "INFO",
        ["PROTECTIVE_RECOVERY_FAILED"] = "ERROR",
        ["PROTECTIVE_EMERGENCY_FLATTEN_TRIGGERED"] = "CRITICAL",
        ["PROTECTIVE_INSTRUMENT_BLOCKED"] = "WARN",
        ["PROTECTIVE_AUDIT_METRICS"] = "INFO",

        // Mismatch escalation (Gap 4)
        ["RECONCILIATION_MISMATCH_DETECTED"] = "WARN",
        ["RECONCILIATION_MISMATCH_PERSISTENT"] = "CRITICAL",
        ["RECONCILIATION_MISMATCH_FAIL_CLOSED"] = "CRITICAL",
        ["RECONCILIATION_MISMATCH_CLEARED"] = "INFO",
        ["RECONCILIATION_MISMATCH_BLOCKED"] = "WARN",
        ["RECONCILIATION_MISMATCH_METRICS"] = "INFO",

        // Slot gate
        ["SLOT_GATE_DIAGNOSTIC"] = "DEBUG",
        
        // Operator
        ["OPERATOR_BANNER"] = "INFO",
        
        // Invariants
        ["INVARIANT_VIOLATION"] = "ERROR",
        ["STREAM_INSTRUMENT_INVARIANT_CHECK"] = "INFO",
        ["STREAM_INSTRUMENT_INVARIANT_MISMATCH"] = "CRITICAL",
        
        // Incident persistence
        ["INCIDENT_PERSIST_ERROR"] = "ERROR",
        
        // Critical execution failures (highest severity)
        ["DUPLICATE_INSTANCE_DETECTED"] = "CRITICAL",
        ["INTENT_POLICY_MISSING_AT_ORDER_CREATE"] = "CRITICAL",
        ["INTENT_NOT_FOUND_FLATTEN_FAILED"] = "CRITICAL",
        ["UNKNOWN_ORDER_FILL_FLATTEN_FAILED"] = "CRITICAL",
        ["UNTRACKED_FILL_FLATTEN_FAILED"] = "CRITICAL",
    };
    
    // All registered event types (for validation)
    private static readonly HashSet<string> _allEvents = new(StringComparer.OrdinalIgnoreCase)
    {
        // Engine lifecycle
        "ENGINE_START", "STARTUP_DEPENDENCY_CHECK_FAILED", "ROBOT_BUILD_SIGNATURE", "ENGINE_STOP", "ENGINE_STAND_DOWN", "ENGINE_TICK_INVALID_STATE",
        "ENGINE_TICK_STALL_DETECTED", "ENGINE_TICK_STALL_STARTUP", "ENGINE_TICK_STALL_RUNTIME", "ENGINE_TICK_STALL_RECOVERED", "ENGINE_TICK_CALLSITE", "ENGINE_TIMER_HEARTBEAT",
        "TIMER_LIFECYCLE_STATE_TRANSITION", "TIMER_LIFECYCLE_START_ATTEMPT", "TIMER_LIFECYCLE_START_SKIPPED", "TIMER_LIFECYCLE_STARTED", "TIMER_LIFECYCLE_ERROR",
        "TIMER_GATE_EARLY_RETURN", "TIMER_META_HEARTBEAT", "TIMER_CALLBACK_EXCEPTION",
        
        // Configuration
        "PROJECT_ROOT_RESOLVED", "LOG_DIR_RESOLVED", "LOGGING_CONFIG_LOADED", "LOGGING_CONFIG_LOAD_FAILED", "SPEC_LOADED",
        "SPEC_INVALID", "SPEC_NAME_LOADED", "HEALTH_MONITOR_CONFIG_LOADED",
        "HEALTH_MONITOR_CONFIG_ERROR", "HEALTH_MONITOR_CONFIG_MISSING", "HEALTH_MONITOR_CONFIG_NULL",
        "HEALTH_MONITOR_DISABLED", "HEALTH_MONITOR_STARTED", "HEALTH_MONITOR_EVALUATION_ERROR",
        "PUSHOVER_CONFIG_MISSING",
        
        // Timetable
        "TIMETABLE_LOADED", "TIMETABLE_UPDATED", "TIMETABLE_VALIDATED", "TIMETABLE_INVALID",
        "TIMETABLE_INVALID_TRADING_DATE", "TIMETABLE_MISSING_TRADING_DATE",
        "TIMETABLE_TRADING_DATE_MISMATCH", "TIMETABLE_APPLY_SKIPPED", "TIMETABLE_PARSING_COMPLETE",
        "TIMETABLE_POLL_STALL_DETECTED", "TIMETABLE_POLL_STALL_RECOVERED",
        
        // Trading date
        "TRADING_DATE_LOCKED",
        
        // Streams
        "STREAMS_CREATED", "STREAMS_CREATION_FAILED", "STREAMS_CREATION_SKIPPED",
        "DUPLICATE_STREAM_ID", "STREAM_STAND_DOWN", "STREAM_SKIPPED",
        
        // Bars
        "BAR_ACCEPTED", "BAR_DATE_MISMATCH", "BAR_PARTIAL_REJECTED",
        "BAR_RECEIVED_BEFORE_DATE_LOCKED", "BAR_RECEIVED_NO_STREAMS",
        "BAR_REJECTION_CONTINUOUS_FUTURE", "BAR_REJECTION_CONTINUOUS_NO_DATE_LOCK",
        "BAR_REJECTION_RATE_HIGH", "BAR_REJECTION_SUMMARY", "BAR_DELIVERY_SUMMARY",
        "BAR_DELIVERY_TO_STREAM", "BAR_ROUTING_DIAGNOSTIC", "BAR_TIME_INTERPRETATION_MISMATCH",
        "BAR_TIME_INTERPRETATION_LOCKED", "BAR_TIME_DETECTION_STARTING",
        "BAR_FLOW_STALLED",
        
        // BarsRequest
        "BARSREQUEST_REQUESTED", "BARSREQUEST_EXECUTED", "BARSREQUEST_FAILED",
        "BARSREQUEST_SKIPPED", "BARSREQUEST_INITIALIZATION", "BARSREQUEST_RANGE_CHECK",
        "BARSREQUEST_RANGE_DETERMINED", "BARSREQUEST_STREAM_STATUS",
        "BARSREQUEST_FILTER_SUMMARY", "BARSREQUEST_UNEXPECTED_COUNT",
        "BARSREQUEST_ZERO_BARS_DIAGNOSTIC",
        
        // Pre-hydration
        "PRE_HYDRATION_BARS_LOADED", "PRE_HYDRATION_BARS_FILTERED",
        "PRE_HYDRATION_BARS_SKIPPED", "PRE_HYDRATION_BARS_SKIPPED_STREAM_STATE",
        "PRE_HYDRATION_BARS_SKIPPED_ACTIVE_STREAM", "PRE_HYDRATION_NO_BARS_AFTER_FILTER",
        "PRE_HYDRATION_WAITING_FOR_BARSREQUEST", "PRE_HYDRATION_COMPLETE_SET", "PRE_HYDRATION_COMPLETE_BLOCK_ENTERED",
        "PRE_HYDRATION_AFTER_COMPLETE_BLOCK", "PRE_HYDRATION_AFTER_VARIABLES",
        "PRE_HYDRATION_BEFORE_RANGE_DIAGNOSTIC", "PRE_HYDRATION_RANGE_START_DIAGNOSTIC",
        "PRE_HYDRATION_HANDLER_TRACE", "PRE_HYDRATION_FAILED",
        
        // Range computation
        "RANGE_LOCKED", "RANGE_COMPUTE_FAILED", "RANGE_COMPUTE_START",
        "RANGE_COMPUTE_NO_BARS_DIAGNOSTIC", "RANGE_COMPUTE_BAR_FILTERING",
        "RANGE_FIRST_BAR_ACCEPTED", "RANGE_INTENT_ASSERT", "RANGE_LOCK_ASSERT",
        "RANGE_INVALIDATED",
        
        // Gap detection
        "BAR_GAP_DETECTED", "GAP_TOLERANCE_VIOLATION", "GAP_TOLERATED",
        
        // Execution
        "EXECUTION_MODE_SET", "EXECUTION_BLOCKED", "EXECUTION_ERROR",         "EXECUTION_FILLED",
        "EXECUTION_PARTIAL_FILL", "EXECUTION_SKIPPED_DUPLICATE",         "EXECUTION_UPDATE_UNKNOWN_ORDER",
        "EXECUTION_UPDATE_ORDER_MAP_RETRY",
        "EXECUTION_UPDATE_SKIPPED_WRONG_INSTANCE", "EXECUTION_UPDATE_WRONG_INSTANCE_DIAGNOSTIC",
        "ENTRY_AGGREGATION_ATTEMPT", "ENTRY_AGGREGATION_SUCCESS", "ENTRY_AGGREGATION_FAILED",
        "AGG_ENTRY_FILL_ALLOCATED",
        "EXECUTION_UPDATE_MOCK", "EXECUTION_SUMMARY_WRITTEN", "EXECUTION_GATE_INVARIANT_VIOLATION",
        "BREAKOUT_DETECTED_ALREADY_ENTERED", "TRADE_COMPLETED",
        "ENTRY_BLOCKED_RISK", "RISK_CHECK_EVALUATED", "POSITION_FLATTEN_FAIL_CLOSED",
        
        // Orders
        "ORDER_SUBMITTED", "ORDER_SUBMIT_SUCCESS", "ORDER_SUBMIT_FAIL", "ORDER_SUBMIT_ATTEMPT",
        "ORDER_ACKNOWLEDGED", "ORDER_REJECTED", "ORDER_CANCELLED", "OCO_SIBLING_CANCELLED", "ENTRY_SUBMITTED",
        "PROTECTIVES_PLACED", "PROTECTIVE_ORDERS_SUBMITTED", "PROTECTIVE_ORDERS_FAILED_FLATTENED",
        "STOP_BRACKETS_SUBMITTED", "STOP_BRACKETS_SUBMIT_ATTEMPT", "STOP_BRACKETS_SUBMIT_FAILED",
        "STOP_MODIFY_ATTEMPT", "STOP_MODIFY_SUCCESS", "STOP_MODIFY_REQUESTED", "STOP_MODIFY_CONFIRMED",
        "STOP_MODIFY_TIMEOUT", "STOP_MODIFY_FAILED", "STOP_MODIFY_FAILED_SNAPSHOT", "STOP_MODIFY_REJECTED", "STOP_MODIFY_PENDING_CLEARED_ON_EXIT",
        "ORDER_UPDATED", "BE_PREFLIGHT_STOP_ORDER_UPDATE",
        "STOP_MODIFY_FAIL", "STOP_MODIFY_SKIPPED", "BE_SKIP_STOP_ALREADY_TIGHTER",
        "BE_TRIGGER_REACHED", "BE_TRIGGER_RETRY_NEEDED", "BE_TRIGGER_FAILED", "BE_TRIGGER_TIMEOUT_ERROR",
        
        // Execution adapters
        "ADAPTER_SELECTED", "SIM_ACCOUNT_VERIFIED", "LIVE_MODE_BLOCKED",
        
        // Kill switch
        "KILL_SWITCH_INITIALIZED", "KILL_SWITCH_ACTIVE", "KILL_SWITCH_ERROR_FAIL_CLOSED",
        
        // Flatten
        "FLATTEN_ATTEMPT", "FLATTEN_SUCCESS", "FLATTEN_FAIL", "FLATTEN_FAILED_ALL_RETRIES", "FLATTEN_DRYRUN",
        
        // Recovery
        "DISCONNECT_FAIL_CLOSED_ENTERED", "DISCONNECT_RECOVERY_STARTED",
        "DISCONNECT_RECOVERY_COMPLETE", "DISCONNECT_RECOVERY_ABORTED",
        "DISCONNECT_RECOVERY_SKIPPED", "DISCONNECT_RECOVERY_WAITING_FOR_SYNC",
        "RECOVERY_ACCOUNT_SNAPSHOT", "RECOVERY_ACCOUNT_SNAPSHOT_FAILED",
        "RECOVERY_ACCOUNT_SNAPSHOT_NULL", "RECOVERY_CANCELLED_ROBOT_ORDERS",
        "RECOVERY_CANCELLED_ROBOT_ORDERS_FAILED",         "RECOVERY_POSITION_RECONCILED",
        "RECOVERY_POSITION_UNMATCHED",         "RECOVERY_PROTECTIVE_ORDERS_PLACED",
        "UNMATCHED_POSITION_POLICY_EVALUATION_STARTED", "UNMATCHED_POSITION_POLICY_CANDIDATE_FOUND", "UNMATCHED_POSITION_POLICY_NO_CANDIDATE",
        "UNMATCHED_POSITION_POLICY_ADOPT_APPROVED", "UNMATCHED_POSITION_POLICY_ADOPT_REJECTED",
        "UNMATCHED_POSITION_POLICY_FLATTEN_TRIGGERED", "UNMATCHED_POSITION_POLICY_ADOPT_COMPLETED",
        "UNMATCHED_POSITION_FLATTEN_RESULT",
        "RECOVERY_STREAM_ORDERS_RECONCILED",
        "RECOVERY_ORDERS_PRESERVED",
        "ENTRY_ORDERS_VERIFIED_PRESENT",
        "ENTRY_ORDERS_MISSING_DETECTED",
        "ENTRY_ORDERS_RESUBMITTED",
        "ENTRY_ORDERS_RESUBMIT_BLOCKED_POSITION_NOT_FLAT",
        "ENTRY_ORDERS_RESUBMIT_POSITION_CHECK_ERROR",
        "RECOVERY_SECOND_RECONCILIATION",
        "RECOVERY_SECOND_RECONCILIATION_ERROR",
        "ENTRY_ORDER_SET_VALID", "ENTRY_ORDER_SET_MISSING", "ENTRY_ORDER_SET_BROKEN",
        "ENTRY_ORDER_SET_DUPLICATE_DETECTED", "ENTRY_ORDER_SET_CANCEL_REQUESTED",
        "ENTRY_ORDER_SET_CANCEL_CONFIRMED", "ENTRY_ORDER_SET_REBUILD_REQUESTED",
        "ENTRY_ORDER_SET_RESUBMIT_SKIPPED_POSITION_EXISTS", "ENTRY_ORDER_SET_RESUBMIT_SKIPPED_VALID_EXISTS",
        "ENTRY_ORDER_SET_REBUILD_BLOCKED_CANCEL_INCOMPLETE",         "ENTRY_ORDER_ACTION_CLEARED_STREAM_INELIGIBLE",
        "ENTRY_ORDER_INVARIANT_VIOLATED",
        "ENTRY_ORDER_RESUBMIT_SKIPPED_BREAKOUT_ALREADY_TRIGGERED",
        "BREAKOUT_INVALIDATED",
        "ENTRY_RESUBMIT_BLOCKED_BREAKOUT",

        // Health monitoring
        "CONNECTION_LOST", "CONNECTION_LOST_SUSTAINED", "CONNECTION_CONTEXT", "CONNECTION_RECOVERED", "CONNECTION_RECOVERED_NOTIFICATION", "CONNECTION_CONFIRMED",
        "DATA_LOSS_DETECTED", "DATA_STALL_RECOVERED",
        
        // Notifications
        "PUSHOVER_NOTIFY_ENQUEUED", "PUSHOVER_ENDPOINT",
        "CRITICAL_EVENT_REPORTED", "CRITICAL_NOTIFICATION_REJECTED", "CRITICAL_NOTIFICATION_SKIPPED", "CRITICAL_DEDUPE_MISSING_RUN_ID",
        "TEST_NOTIFICATION_SENT", "TEST_NOTIFICATION_SKIPPED", "TEST_NOTIFICATION_TRIGGER_ERROR",
        
        // Journal
        "JOURNAL_WRITTEN", "EXECUTION_JOURNAL_ERROR", "EXECUTION_JOURNAL_READ_ERROR", "EXECUTION_JOURNAL_CORRUPTION", "EXECUTION_SLIPPAGE_DETECTED",
        
        // Reconciliation
        "TRADE_RECONCILED", "RECONCILIATION_SKIPPED_HAS_WORKING_ORDERS", "RECONCILIATION_PASS_SUMMARY", "RECONCILIATION_QTY_MISMATCH", "RECONCILIATION_CONTEXT",
        "RECONCILIATION_ORDER_SOURCE_BREAKDOWN",
        
        // Slot persistence
        "FORCED_FLATTEN_MARKET_CLOSE", "FORCED_FLATTEN_TRIGGERED", "FORCED_FLATTEN_POSITION_CLOSED", "FORCED_FLATTEN_ORDERS_CANCELLED",
        "FORCED_FLATTEN_FAILED", "FORCED_FLATTEN_RETRY", "FORCED_FLATTEN_EXPOSURE_REMAINING", "MANUAL_FLATTEN_REQUIRED", "FORCED_FLATTEN_ORDERS_CANCEL_ERROR", "FORCED_FLATTEN_VERIFY_ERROR",
        "SESSION_CLOSE_RESOLVED", "SESSION_CLOSE_HOLIDAY",
        "REENTRY_SUBMITTED", "REENTRY_FILLED",
        "REENTRY_PROTECTION_ACCEPTED", "REENTRY_FAILED", "REENTRY_PROTECTION_FAILED",
        "SLOT_EXPIRED", "SLOT_STATUS_CHANGED", "SLOT_FAILED_RUNTIME",
        
        // Intent exposure coordinator
        "INTENT_EXPOSURE_REGISTERED", "INTENT_EXPOSURE_CLOSED", "INTENT_EXIT_FILL", "INTENT_EXIT_FILL_NO_EXPOSURE",
        "INTENT_EXIT_VALIDATION_FAILED", "INTENT_PROTECTIVE_FAILURE", "INTENT_PROTECTIVE_FAILURE_FALLBACK",
        "BROKER_EXPOSURE_MISMATCH", "BROKER_EXPOSURE_RECALC_ERROR",
        "CANCEL_INTENT_ORDERS_BLOCKED", "CANCEL_INTENT_ORDERS_MOCK", "CANCEL_INTENT_ORDERS_SUCCESS", "CANCEL_INTENT_ORDERS_ERROR",
        "FLATTEN_INTENT_ATTEMPT", "FLATTEN_INTENT_SUCCESS", "FLATTEN_INTENT_ERROR",
        "FLATTEN_EMERGENCY_ON_BLOCK", "FLATTEN_EMERGENCY_ON_BLOCK_FAILED",
        "DUPLICATE_INSTANCE_DETECTED", "INTENT_POLICY_MISSING_AT_ORDER_CREATE",
        "INTENT_NOT_FOUND_FLATTEN_FAILED", "UNKNOWN_ORDER_FILL_FLATTEN_FAILED",
        "UNTRACKED_FILL_FLATTEN_FAILED",
        
        // Logging service
        "LOG_BACKPRESSURE_DROP", "LOG_PIPELINE_METRIC", "LOG_WORKER_LOOP_ERROR", "LOG_WRITE_FAILURE",
        "LOG_HEALTH_ERROR", "LOG_CONVERSION_ERROR", "LOGGER_CONVERSION_ERROR", "LOGGER_CONVERSION_RETURNED_NULL",
        "LOGGING_INVARIANT_VIOLATION", "UNREGISTERED_EVENT_TYPE", "EXECUTION_EVENT_WRITE_FAILED",
        
        // Notification failures
        "NOTIFICATION_SEND_FAILED",
        
        // Account snapshots
        "ACCOUNT_SNAPSHOT_DRYRUN", "ACCOUNT_SNAPSHOT_ERROR", "ACCOUNT_SNAPSHOT_LIVE_ERROR",
        "ACCOUNT_SNAPSHOT_LIVE_STUB",
        
        // Order cancellation
        "CANCEL_ROBOT_ORDERS_DRYRUN", "CANCEL_ROBOT_ORDERS_ERROR",
        "CANCEL_ROBOT_ORDERS_LIVE_ERROR", "CANCEL_ROBOT_ORDERS_LIVE_STUB",
        "CANCEL_ROBOT_ORDERS_MOCK", "ROBOT_ORDERS_CANCELLED",
        
        // DRYRUN events
        "ENTRY_ORDER_DRYRUN", "STOP_ENTRY_ORDER_DRYRUN", "PROTECTIVE_STOP_DRYRUN",
        "TARGET_ORDER_DRYRUN", "BE_MODIFY_DRYRUN", "BE_PATH_ACTIVE", "BE_FILTER_EXCLUDED_ACTIVE_EXPOSURE", "ONMARKETDATA_LAST_DIAG",
        "BE_GATE_BLOCKED", "BE_ACCOUNT_EXPOSURE_WITHOUT_INTENT", "BE_INACTIVE_WHILE_EXPOSED",
        "BE_MODIFY_MAX_RETRIES_EXCEEDED", "BE_TICK_STALE_WARNING",
        "BE_TRIGGER_REACHED", "BE_TRIGGER_RETRY_NEEDED", "BE_TRIGGER_FAILED", "BE_TRIGGER_TIMEOUT_ERROR",
        
        // Tick/stream state
        "UPDATE_APPLIED",
        
        // Session
        "SESSION_START_TIME_SET",
        
        // Gaps
        "GAP_VIOLATIONS_SUMMARY",
        
        // Slot gate
        "SLOT_GATE_DIAGNOSTIC",
        
        // Operator
        "OPERATOR_BANNER",
        
        // Invariants
        "INVARIANT_VIOLATION", "STREAM_INSTRUMENT_INVARIANT_CHECK", "STREAM_INSTRUMENT_INVARIANT_MISMATCH",
        
        // Incident persistence
        "INCIDENT_PERSIST_ERROR",
        
        // Critical execution failures
        "FLATTEN_FAILED_ALL_RETRIES", "DUPLICATE_INSTANCE_DETECTED",
        "INTENT_POLICY_MISSING_AT_ORDER_CREATE", "INTENT_NOT_FOUND_FLATTEN_FAILED",
        "UNKNOWN_ORDER_FILL_FLATTEN_FAILED", "UNTRACKED_FILL_FLATTEN_FAILED",
        "EXECUTION_COMMAND_STALLED", "EXECUTION_QUEUE_POISON_DETECTED",
        "PROTECTIVE_AUDIT_OK", "PROTECTIVE_AUDIT_FAILED", "PROTECTIVE_MISSING_STOP",
        "PROTECTIVE_STOP_QTY_MISMATCH", "PROTECTIVE_STOP_PRICE_INVALID",
        "PROTECTIVE_MISSING_TARGET", "PROTECTIVE_TARGET_QTY_MISMATCH",
        "PROTECTIVE_CONFLICTING_ORDERS", "PROTECTIVE_RECOVERY_STARTED",
        "PROTECTIVE_RECOVERY_SUBMITTED", "PROTECTIVE_RECOVERY_CONFIRMED",
        "PROTECTIVE_RECOVERY_FAILED", "PROTECTIVE_EMERGENCY_FLATTEN_TRIGGERED",
        "PROTECTIVE_INSTRUMENT_BLOCKED", "PROTECTIVE_AUDIT_METRICS",
        "RECONCILIATION_MISMATCH_DETECTED", "RECONCILIATION_MISMATCH_PERSISTENT",
        "RECONCILIATION_MISMATCH_FAIL_CLOSED", "RECONCILIATION_MISMATCH_CLEARED",
        "RECONCILIATION_MISMATCH_BLOCKED", "RECONCILIATION_MISMATCH_METRICS",
    };
}
