#!/usr/bin/env python3
"""
Regenerate data/analyzed from data/translated using the committed analyzer code.

Use when analyzed data is corrupted or was generated by a different analyzer version
(e.g. one that added 08:30 after the commit). This produces correct data matching the
current (committed) code.

Steps:
  1. Clear data/analyzed (remove all stream parquet files)
  2. Reset merger_processed.json (clear analyzer list so merger will reprocess)
  3. Clear data/analyzer_temp (remove stale/wrong output)
  4. Run analyzer on all translated data (PIPELINE_RUN=1 → outputs to analyzer_temp)
  5. Run merger (merges analyzer_temp → data/analyzed)
  6. Rebuild master matrix

Usage:
  python scripts/regenerate_analyzed_from_translated.py
"""
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
ANALYZED_DIR = BASE / "data" / "analyzed"
ANALYZER_TEMP_DIR = BASE / "data" / "analyzer_temp"
TRANSLATED_DIR = BASE / "data" / "translated"
PROCESSED_LOG = BASE / "data" / "merger_processed.json"


def clear_analyzed():
    """Remove all parquet files and stream dirs from data/analyzed."""
    if not ANALYZED_DIR.exists():
        return 0
    removed = 0
    for item in ANALYZED_DIR.iterdir():
        if item.is_dir():
            shutil.rmtree(item)
            removed += 1
            print(f"  Removed {item.relative_to(BASE)}")
    return removed


def reset_merger_log():
    """Clear analyzer entries from merger_processed.json so merger will reprocess."""
    if not PROCESSED_LOG.exists():
        return
    with open(PROCESSED_LOG) as f:
        log = json.load(f)
    for key in ["analyzer", "manual_analyzer"]:
        if key in log and log[key]:
            log[key] = []
            print(f"  Cleared merger log '{key}'")
    with open(PROCESSED_LOG, "w") as f:
        json.dump(log, f, indent=2)


def clear_analyzer_temp():
    """Remove all folders from data/analyzer_temp."""
    if not ANALYZER_TEMP_DIR.exists():
        return 0
    removed = 0
    for item in ANALYZER_TEMP_DIR.iterdir():
        if item.is_dir():
            shutil.rmtree(item)
            removed += 1
    if removed:
        print(f"  Cleared {removed} folder(s) from analyzer_temp")
    return removed


def run_analyzer():
    """Run parallel analyzer on all translated data."""
    if not TRANSLATED_DIR.exists():
        print("ERROR: data/translated not found")
        return False
    env = os.environ.copy()
    env["PIPELINE_RUN"] = "1"
    cmd = [
        sys.executable,
        str(BASE / "tools" / "run_analyzer_parallel.py"),
        "--folder", str(TRANSLATED_DIR),
        "--instruments", "ES", "NQ", "YM", "CL", "NG", "GC", "RTY",
    ]
    print("  Running analyzer (all instruments)...")
    result = subprocess.run(cmd, cwd=str(BASE), env=env)
    return result.returncode == 0


def run_merger():
    """Run data merger."""
    cmd = [sys.executable, str(BASE / "modules" / "merger" / "merger.py")]
    print("  Running merger...")
    result = subprocess.run(cmd, cwd=str(BASE))
    return result.returncode == 0


def run_matrix():
    """Rebuild master matrix."""
    script = BASE / "scripts" / "maintenance" / "run_matrix_and_timetable.py"
    if not script.exists():
        print("  Could not find matrix script")
        return False
    print("  Rebuilding master matrix...")
    result = subprocess.run([sys.executable, str(script)], cwd=str(BASE))
    return result.returncode == 0


def main():
    print("Regenerating data/analyzed from data/translated")
    print("=" * 60)

    print("1. Clearing data/analyzed...")
    clear_analyzed()

    print("2. Resetting merger_processed.json...")
    reset_merger_log()

    print("3. Clearing analyzer_temp...")
    clear_analyzer_temp()

    print("4. Running analyzer (this may take several minutes)...")
    if not run_analyzer():
        print("ERROR: Analyzer failed")
        sys.exit(1)

    print("5. Running merger...")
    if not run_merger():
        print("ERROR: Merger failed")
        sys.exit(1)

    print("6. Rebuilding master matrix...")
    if not run_matrix():
        print("ERROR: Matrix rebuild failed")
        sys.exit(1)

    print("=" * 60)
    print("Done. data/analyzed has been regenerated from translated data.")


if __name__ == "__main__":
    main()
